A=[
("Graffiti-Künstler von Farbaholix sprüht ein großes Schwarz-Weiß-Mural vom Gerüst aus","Farbaholix graffiti artist spray-painting a large black-and-white mural from scaffolding","Художник Farbaholix расписывает баллончиком большой чёрно-белый мурал со строительных лесов"),
("Fassadengestaltung mit grafischen Streifen – Arbeit mit Hubsteiger an einem mehrstöckigen Gebäude","Facade design with graphic stripes – painting a multi-storey building from an aerial work platform","Роспись фасада графическими полосами: работа с автовышки на многоэтажном здании"),
("Künstler sprüht eine Meeresschildkröte auf eine blaue Ziegelwand","Artist spray-painting a sea turtle on a blue brick wall","Художник рисует баллончиком морскую черепаху на синей кирпичной стене"),
("Wandbild: weiße Schachfigur Springer in einem Rundbogen, Schriftzug „Kінь / Knight“","Mural: white chess knight inside an arch with the lettering “Кінь / Knight”","Мурал: белый шахматный конь в арке, надпись «Кінь / Knight»"),
("Großes Fassaden-Mural mit Skatern und BMX-Fahrer, Schriftzug „Wir sind hier, um zu kreieren!“","Large facade mural with skaters and a BMX rider, lettering “We are here to create!”","Большой мурал на фасаде со скейтерами и BMX-райдером, надпись «Мы здесь, чтобы творить!»"),
("Billardraum mit Schwarz-Weiß-Porträts im Gangster-Film-Stil an der Wand","Billiard room with black-and-white gangster-film portraits painted on the wall","Бильярдная с чёрно-белыми портретами в стиле гангстерского кино на стене"),
("Neon-Innenraumgestaltung einer Shisha-Lounge mit UV-Farben, Lippen-Motiven und 3D-Köpfen","Neon interior design of a hookah lounge with UV paint, lip motifs and 3D heads","Неоновый интерьер кальянной: УФ-краски, мотивы губ и 3D-головы"),
("Wandgestaltung in großer Höhe: rote Streifen in einem Sportzentrum, Arbeit vom Gerüst","High-level wall painting: red stripes in a sports centre, painted from scaffolding","Роспись на высоте: красные полосы в спортивном центре, работа с лесов"),
("Empfangsbereich eines Sportzentrums mit roten Diagonalstreifen und Logo an der Wand","Sports centre reception with red diagonal stripes and a logo painted on the wall","Ресепшен спортивного центра: красные диагональные полосы и логотип на стене"),
("Basketballhalle mit dynamischer Wandgestaltung aus farbigen Streifen und Logo","Basketball hall with dynamic wall design of coloured stripes and a logo","Баскетбольный зал с динамичной росписью из цветных полос и логотипом"),
("Hip-Hop-Porträtwand mit Erykah Badu, MC Fame und The Notorious B.I.G. in einer Shisha-Bar","Hip-hop portrait wall with Erykah Badu, MC Fame and The Notorious B.I.G. in a hookah bar","Стена с портретами хип-хоп-артистов: Erykah Badu, MC Fame и The Notorious B.I.G. в кальянной"),
("Büro-Wandgestaltung: Weltkarte mit Objektfotos im RE/MAX-Immobilienbüro","Office wall design: world map with property photos in a RE/MAX real-estate office","Роспись офиса: карта мира с фото объектов в агентстве недвижимости RE/MAX"),
("UV-Wandbild: riesiger Gamecontroller mit neongrünen Farbspritzern","UV mural: giant game controller with neon-green paint splashes","УФ-мурал: огромный геймпад с неоново-зелёными брызгами"),
("Lasertag-Arena mit psychedelischer UV-Wandmalerei","Laser tag arena with psychedelic UV wall painting","Лазертаг-арена с психоделической УФ-росписью"),
("Lasertag-Arena: leuchtende Feuerportale in UV-Farbe auf Trennwänden","Laser tag arena: glowing fire portals in UV paint on partition walls","Лазертаг-арена: светящиеся огненные порталы УФ-краской на перегородках"),
("Gaming-Raum mit Regenbogen-Farbverläufen und Drip-Effekt an den Wänden","Gaming room with rainbow gradients and drip effect on the walls","Игровая комната: радужные переходы и эффект подтёков на стенах"),
("Fitnessstudio-Wandbild: Bodybuilder in Schwarz-Weiß vor rotem Hintergrund","Gym mural: black-and-white bodybuilder on a red background","Мурал в спортзале: чёрно-белый бодибилдер на красном фоне"),
("Wohnzimmer mit geometrischer Wandgestaltung aus schwarzen und grauen Dreiecken","Living room with geometric wall design of black and grey triangles","Гостиная с геометрической росписью из чёрных и серых треугольников"),
("Lounge mit Sitzsäcken, geometrischen Wänden und gemaltem blauen Sportwagen","Lounge with bean bags, geometric walls and a painted blue sports car","Лаунж с креслами-мешками, геометрическими стенами и нарисованным синим спорткаром"),
("Airbrush-Wandgestaltung: weißer Rauch auf schwarzer Wand in einer Shisha-Bar","Airbrush wall design: white smoke on a black wall in a hookah bar","Аэрография: белый дым на чёрной стене в кальянной"),
("Flur einer Lounge mit UV-Comicfiguren und Sternbildern an dunklen Wänden","Lounge corridor with UV cartoon characters and constellations on dark walls","Коридор лаунжа: УФ-мультяшные персонажи и созвездия на тёмных стенах"),
("Graffiti-Künstler sprüht eine große Meeresschildkröte auf eine Ziegelwand","Graffiti artist spray-painting a large sea turtle on a brick wall","Граффити-художник рисует большую морскую черепаху на кирпичной стене"),
("Unterwasser-Mural mit Walen, Fischen und Eisbär an der Fassade eines Aquaparks","Underwater mural with whales, fish and a polar bear on an aquapark facade","Подводный мурал с китами, рыбами и белым медведем на фасаде аквапарка"),
("Unterwasser-Fassadenbild: Eisbär, Meeresschildkröte und Korallen","Underwater facade mural: polar bear, sea turtle and corals","Подводная роспись фасада: белый медведь, морская черепаха и кораллы"),
("Eingangsbereich eines Aquaparks mit Papagei und Palmen im Dschungel-Stil","Aquapark entrance painted with a parrot and palm trees in jungle style","Вход в аквапарк: попугай и пальмы в стиле джунглей"),
("Dachbemalung „Musica del Mar“ mit Notenschlüssel, Kinburn","Roof painting “Musica del Mar” with a treble clef, Kinburn","Роспись крыши «Musica del Mar» со скрипичным ключом, Кинбурн"),
("Künstler malt einen realistischen KTM X-Bow Sportwagen an eine Wand","Artist painting a realistic KTM X-Bow sports car on a wall","Художник рисует реалистичный спорткар KTM X-Bow на стене"),
("Detail: realistische rote Rose, mit Sprühdose gemalt","Detail: realistic red rose painted with spray paint","Деталь: реалистичная красная роза, нарисованная баллончиком"),
("Wandbild eines Kriegsschiffs auf einer Mauer in Mykolajiw","Mural of a warship on a wall in Mykolaiv","Мурал с военным кораблём на стене в Николаеве"),
("Logo-Wandbild „Rainbow Ecosystem“ auf einer Firmenfassade","“Rainbow Ecosystem” logo mural on a company facade","Логотип «Rainbow Ecosystem» на фасаде компании"),
("Fassaden-Mural mit Wellen und Tauben in Rüsselsheim – Slavik und Maik von Farbaholix","Facade mural with waves and doves in Rüsselsheim – Slavik and Maik of Farbaholix","Мурал на фасаде с волнами и голубями в Рюссельсхайме: Славик и Майк, Farbaholix"),
("Fassade eines Sportzentrums mit grafischen Streifen und Sportler-Figuren","Sports centre facade with graphic stripes and athlete figures","Фасад спортивного центра с графическими полосами и фигурами спортсменов"),
("Minimalistisches Fassaden-Mural mit Palmensilhouetten an einem Aquapark","Minimalist facade mural with palm silhouettes on an aquapark","Минималистичный мурал на фасаде аквапарка с силуэтами пальм"),
("Detail einer Fassade: Palmenschatten in Orange, Graffiti in Henitschesk","Facade detail: palm shadows in orange, graffiti in Henichesk","Деталь фасада: тени пальм в оранжевых тонах, граффити в Геническе"),
("Realistisches Graffiti eines Rolls-Royce-Oldtimers, Koblewo","Realistic graffiti of a vintage Rolls-Royce, Koblevo","Реалистичное граффити: ретро-автомобиль Rolls-Royce, Коблево"),
("Detail einer Fassadengestaltung: leuchtendes Blatt-Feuer-Motiv, Graffiti von 2010","Facade detail: glowing leaf-and-fire motif, graffiti from 2010","Деталь фасада: светящийся мотив листа и огня, граффити 2010 года"),
("Individuell bemalte Sneaker (Custom Sneakers) von Maik, Farbaholix","Hand-painted custom sneakers by Maik of Farbaholix","Кастомные кроссовки, расписанные вручную Майком из Farbaholix"),
("Kalligrafie „Vielen Dank“ in Violett, gerahmt","Calligraphy “Vielen Dank” in purple, framed","Каллиграфия «Vielen Dank» фиолетовым, в рамке"),
("Kunstinstallation „Used for Art“ aus leeren Sprühdosen, Ausstellung","Art installation “Used for Art” made of empty spray cans, exhibition","Арт-инсталляция «Used for Art» из пустых баллончиков, выставка"),
("Zwei BMX-Räder im Graffiti-Stil bemalt","Two BMX bikes painted in graffiti style","Два BMX-велосипеда, расписанные в стиле граффити"),
("Custom Sneaker: weißer Schuh mit roten Blumenzeichnungen, von Maik","Custom sneaker: white shoe with red floral drawings, by Maik","Кастомные кроссовки: белая пара с красными цветочными рисунками, автор Майк"),
("Bemalter Spiegel als Fotozone in einem Kinder-Friseursalon","Painted mirror as a photo spot in a children’s barbershop","Расписанное зеркало для фотозоны в детской парикмахерской"),
("Leuchtende 3D-Buchstaben mit App-gesteuerter LED-Beleuchtung, Frankfurt","Illuminated 3D letters with app-controlled LED lighting, Frankfurt","Светящиеся 3D-буквы с LED-подсветкой, управляемой через приложение, Франкфурт"),
("Graffiti-Workshop für Kinder im Internationalen Kinderhaus Frankfurt","Graffiti workshop for children at Internationales Kinderhaus Frankfurt","Граффити-воркшоп для детей в Internationales Kinderhaus во Франкфурте"),
("Graffiti-Schule: Jugendliche sprühen gemeinsam an einer Wand","Graffiti school: teenagers spray-painting together on a wall","Школа граффити: подростки вместе рисуют на стене"),
("Slavik und Maik mit Kindern nach dem Workshop im Internationalen Kinderhaus Frankfurt","Slavik and Maik with children after the workshop at Internationales Kinderhaus Frankfurt","Славик и Майк с детьми после воркшопа в Internationales Kinderhaus, Франкфурт"),
("Kinder-Workshop: Gruppe mit selbst gesprühten Buchstaben","Kids’ workshop: group holding their own spray-painted letters","Детский воркшоп: группа с буквами, которые дети нарисовали сами"),
("Hip-Hop-Workshop im Freien in Darmstadt","Outdoor hip-hop workshop in Darmstadt","Хип-хоп-воркшоп на открытом воздухе в Дармштадте"),
("Sprühdose Montana MTN 94 beim Malen eines Musters","Montana MTN 94 spray can while painting a pattern","Баллончик Montana MTN 94 в процессе рисования узора"),
("Workshop: Buchstaben-Technik mit MTN 94 üben","Workshop: practising lettering technique with MTN 94","Воркшоп: отработка техники букв с MTN 94"),
("Workshop: junge Teilnehmerin macht ihre ersten Schritte mit der Sprühdose","Workshop: young participant taking her first steps with a spray can","Воркшоп: юная участница делает первые шаги с баллончиком"),
("Workshop: junge Teilnehmerin sprüht klassisches Graffiti","Workshop: young participant spray-painting classic graffiti","Воркшоп: юная участница рисует классическое граффити"),
("Fotorealismus-Workshop: realistischer Nike-Sneaker als Graffiti","Photorealism workshop: realistic Nike sneaker as graffiti","Воркшоп по фотореализму: реалистичная кроссовка Nike в граффити"),
("Benedikt Sons, Mitgründer und CEO der Cansativa Group","Benedikt Sons, co-founder and CEO of Cansativa Group","Бенедикт Зонс, сооснователь и CEO Cansativa Group"),
("Robert Lempka, Geschäftsführer des FSV Frankfurt","Robert Lempka, managing director of FSV Frankfurt","Роберт Лемпка, управляющий директор FSV Frankfurt"),
("Dr. Stefan Söhngen, Speaker und Autor","Dr. Stefan Söhngen, speaker and author","Д-р Штефан Зёнген, спикер и автор"),
]
