CALC = {
'de': dict(
  menu='Preisrechner',
  meta=('Graffiti-Kostenrechner: Was kostet ein Mural? | Farbaholix',
        'Was kostet ein Graffiti oder Mural? In 30 Sekunden zum Richtwert: Fläche, Motiv, Höhe, Termin – Preisrechner von Farbaholix, Graffiti-Künstler in Frankfurt.'),
  kicker='Preisrechner', h1='Was kostet Ihr Graffiti? Richtwert in 30 Sekunden',
  lead='Beantworten Sie ein paar kurze Fragen – der Richtwert für Ihre Wand erscheint sofort. Unverbindlich, ohne Anmeldung.',
  locale='de-DE',
  q=dict(what='Was soll gestaltet werden?', area='Fläche', detail='Detailgrad', height='Arbeitshöhe', design='Entwurf', surface='Zustand der Wand',
         when='Wann?', where='Wo?', extras='Extras'),
  o=dict(
    what=[('facade', 'Fassade / Außenwand'), ('indoor', 'Innenwand / Raum'), ('concept', 'Mehrere Räume / Gesamtkonzept'), ('object', 'Objekt (Leinwand, Tür, Möbel …)'), ('toilet', 'Nur eine Toilette')],
    detail=[('low', 'Einfach – Schrift, Logo, grafisch'), ('medium', 'Mittel – Illustration, Graffiti-Stil'), ('high', 'Komplex – Fotorealistisch, detailliert')],
    height=[('h1', 'bis 3 m'), ('h2', '3–6 m (Gerüst)'), ('h3', 'über 6 m (Hubsteiger)')],
    design=[('ready', 'Wir haben einen fertigen Entwurf'), ('ours', 'Farbaholix entwirft')],
    surface=[('ready', 'glatt & bereit'), ('clean', 'reinigen & grundieren'), ('repair', 'Schäden ausbessern')],
    when=[('flex', 'flexibel'), ('normal', 'in 2–4 Wochen'), ('fast', 'unter 2 Wochen'), ('express', 'unter 1 Woche')],
    where=[('ffm', 'Frankfurt am Main'), ('r30', 'bis 30 km'), ('r100', '30–100 km'), ('r300', '100–300 km'), ('far', 'weiter / Ausland')]),
  extras=[('hiphop', 'Projekt mit Hip-Hop-Bezug'), ('visible', 'Stark frequentierter Ort (bringt uns neue Kunden)'), ('ukraine', '+10 % für ukrainische Underground-Künstler (DJs, B-Boys, MCs, Writer)')],
  result_t='Ihr Richtwert', net='netto', gross='{lo} – {hi} inkl. 19 % MwSt.',
  days='Arbeitszeit ca.', daysUnit='Künstlertage', designRow='Entwurf (10 %)', discRow='Kultur-/Sichtbarkeits-Rabatt', uaRow='Unterstützung Ukraine (10 %)', minRow='Mindestauftrag',
  design_note='Zahlung: 10 % Anzahlung für die Entwürfe (nicht erstattbar, Teil des Budgets), 50 % nach Freigabe der Entwürfe, 40 % nach Fertigstellung.',
  payRows=['Anzahlung Entwurf (10 %)', 'Nach Freigabe (50 %)', 'Nach Fertigstellung (40 %)'], hiphopRow='Hip-Hop-Projekt: auch unter 1.000 € möglich', mail='oder per E-Mail senden',
  disclaimer='Unverbindlicher Richtwert inkl. Material. Den Festpreis erhalten Sie nach dem Vor-Ort-Termin.',
  beta=("Wichtig", "Unser Preisrechner befindet sich noch in der Lern- und Entwicklungsphase – eine Beta-Version. Die berechneten Beträge können deutlich von realistischen Preisen abweichen. Wir arbeiten intensiv daran und werden uns schon bald selbst auf die Ergebnisse dieses Rechners verlassen. Vielen Dank für Ihr Verständnis."),
  cta='Anfrage mit Richtwert senden',
  stop_t='Das machen wir leider nicht.', stop_p='Reine Toiletten-Gestaltungen bieten wir nicht an. Wenn Sie weitere Räume oder Flächen planen, wählen Sie oben eine andere Option.',
  briefTitle='Anfrage aus dem Preisrechner', briefPrice='Richtwert',
  faq=[('Was kostet ein Graffiti pro Quadratmeter?', 'Einen festen Quadratmeterpreis gibt es nicht. Entscheidend sind Detailgrad, Höhe, Untergrund und Termin – grafische Motive sind pro Quadratmeter deutlich günstiger als Fotorealismus. Der Rechner zeigt Ihnen einen Richtwert für Ihr Projekt.'),
       ('Ist der Preis im Rechner verbindlich?', 'Nein, er ist ein Richtwert. Nach einem Vor-Ort-Termin erhalten Sie ein verbindliches Festpreisangebot.'),
       ('Was ist im Preis enthalten?', 'Arbeitszeit, Farben (Caparol, Montana Colors) und Anfahrt. Gerüst oder Hubsteiger werden bei Bedarf gesondert abgestimmt.'),
       ('Wie wird bezahlt?', '10 % des Budgets als Anzahlung für die Entwürfe – nicht erstattbar, aber Teil des Gesamtpreises. 50 % nach Freigabe der Entwürfe, 40 % nach Fertigstellung. Alle Preise zzgl. 19 % MwSt.'),
       ('Gibt es einen Mindestauftrag?', 'Ja, 1.000 € netto. Für Projekte mit Hip-Hop-Bezug machen wir Ausnahmen – dann geht es auch darunter.')],
  teaser_t='Was kostet die Gestaltung Ihrer Wand?', teaser_p='Fläche, Motiv, Termin – in 30 Sekunden zum Richtwert. Unverbindlich.', teaser_a='Zum Preisrechner',
),
'en': dict(
  menu='Price calculator',
  meta=('Graffiti Cost Calculator: How Much Does a Mural Cost? | Farbaholix',
        'How much does a graffiti or mural cost? Get an estimate in 30 seconds: size, motif, height, deadline – price calculator by Farbaholix, graffiti artist in Frankfurt.'),
  kicker='Price calculator', h1='How much does your graffiti cost? Estimate in 30 seconds',
  lead='Answer a few quick questions – the estimate for your wall appears instantly. No obligation, no sign-up.',
  locale='en-GB',
  q=dict(what='What should be painted?', area='Area', detail='Detail level', height='Working height', design='Design', surface='Wall condition',
         when='When?', where='Where?', extras='Extras'),
  o=dict(
    what=[('facade', 'Facade / outside wall'), ('indoor', 'Indoor wall / room'), ('concept', 'Several rooms / full concept'), ('object', 'Object (canvas, door, furniture …)'), ('toilet', 'Just a toilet')],
    detail=[('low', 'Simple – lettering, logo, graphic'), ('medium', 'Medium – illustration, graffiti style'), ('high', 'Complex – photorealistic, detailed')],
    height=[('h1', 'up to 3 m'), ('h2', '3–6 m (scaffold)'), ('h3', 'over 6 m (lift)')],
    design=[('ready', 'We have a finished design'), ('ours', 'Farbaholix designs it')],
    surface=[('ready', 'smooth & ready'), ('clean', 'clean & prime'), ('repair', 'repair damage')],
    when=[('flex', 'flexible'), ('normal', 'in 2–4 weeks'), ('fast', 'under 2 weeks'), ('express', 'under 1 week')],
    where=[('ffm', 'Frankfurt am Main'), ('r30', 'up to 30 km'), ('r100', '30–100 km'), ('r300', '100–300 km'), ('far', 'further / abroad')]),
  extras=[('hiphop', 'Project connected to hip-hop'), ('visible', 'High-traffic location (brings us new clients)'), ('ukraine', '+10 % for Ukrainian underground artists (DJs, b-boys, MCs, writers)')],
  result_t='Your estimate', net='net', gross='{lo} – {hi} incl. 19 % VAT',
  days='Working time approx.', daysUnit='artist days', designRow='Design (10 %)', discRow='Culture/visibility discount', uaRow='Support for Ukraine (10 %)', minRow='Minimum order',
  design_note='Payment: 10 % deposit for the designs (non-refundable, part of the budget), 50 % after design approval, 40 % on completion.',
  payRows=['Design deposit (10 %)', 'After approval (50 %)', 'On completion (40 %)'], hiphopRow='Hip-hop project: below €1,000 possible', mail='or send by e-mail',
  disclaimer='Non-binding estimate incl. materials. You get a fixed price after the site visit.',
  beta=("Important", "Our price calculator is still learning and in development – a beta version. The figures it shows may differ significantly from realistic prices. We are actively working on it and will soon rely on its results ourselves. Thank you for your understanding."),
  cta="Send enquiry with estimate",
  stop_t="Sorry, we don't do that.", stop_p="We don't take on toilet-only designs. If you are planning other rooms or surfaces, choose another option above.",
  briefTitle='Enquiry from the price calculator', briefPrice='Estimate',
  faq=[('How much does graffiti cost per square metre?', 'There is no fixed price per square metre. Detail, height, surface and deadline matter most – graphic motifs cost much less per square metre than photorealism. The calculator gives you an estimate for your project.'),
       ('Is the calculator price binding?', 'No, it is an estimate. After a site visit you receive a binding fixed-price quote.'),
       ('What is included?', 'Working time, paints (Caparol, Montana Colors) and travel. Scaffolding or a lift is agreed separately if needed.'),
       ('How is payment made?', '10 % of the budget as a deposit for the designs – non-refundable but part of the total price. 50 % after design approval, 40 % on completion. All prices plus 19 % VAT.'),
       ('Is there a minimum order?', 'Yes, €1,000 net. For projects connected to hip-hop we make exceptions – then it can be less.')],
  teaser_t='How much does it cost to paint your wall?', teaser_p='Size, motif, deadline – an estimate in 30 seconds. No obligation.', teaser_a='Open the price calculator',
),
'uk': dict(
  menu="Калькулятор ціни",
  meta=("Калькулятор вартості графіті: скілько коштує мурал? | Farbaholix",
        "Скільки коштує графіті чи мурал? Орієнтовна ціна за 30 секунд: площа, мотив, висота, термін – калькулятор Farbaholix, графіті-художника у Франкфурті."),
  kicker="Калькулятор ціни", h1="Скільки коштує ваше графіті? Орієнтир за 30 секунд",
  lead="Дайте кілька коротких відповідей – орієнтовна ціна для вашої стіни з'явиться одразу. Без зобов'язань і реєстрації.",
  locale="uk-UA",
  q=dict(what="Що потрібно розписати?", area="Площа", detail="Рівень деталізації", height="Висота робіт", design="Ескіз", surface="Стан стіни",
         when="Коли?", where="Де?", extras="Додатково"),
  o=dict(
    what=[("facade", "Фасад / зовнішня стіна"), ("indoor", "Стіна в приміщенні"), ("concept", "Кілька приміщень / цілісна концепція"), ("object", "Об'єкт (полотно, двері, меблі …)"), ("toilet", "Лише туалет")],
    detail=[("low", "Простий – напис, логотип, графіка"), ("medium", "Середній – ілюстрація, графіті-стиль"), ("high", "Складний – фотореалізм, деталізований")],
    height=[("h1", "до 3 м"), ("h2", "3–6 м (риштування)"), ("h3", "понад 6 м (автовишка)")],
    design=[("ready", "У нас є готовий ескіз"), ("ours", "Ескіз робить Farbaholix")],
    surface=[("ready", "рівна й готова"), ("clean", "очистити й загрунтувати"), ("repair", "відремонтувати пошкодження")],
    when=[("flex", "гнучко"), ("normal", "за 2–4 тижні"), ("fast", "менше ніж за 2 тижні"), ("express", "менше ніж за тиждень")],
    where=[("ffm", "Франкфурт-на-Майні"), ("r30", "до 30 км"), ("r100", "30–100 км"), ("r300", "100–300 км"), ("far", "далі / за кордоном")]),
  extras=[("hiphop", "Проєкт пов'язаний із хіп-хопом"), ("visible", "Людне місце (приведе нам нових клієнтів)"), ("ukraine", "+10 % на підтримку українських андеґраунд-артистів (DJ, бі-бої, MC, райтери)")],
  result_t="Ваш орієнтир", net="нетто", gross="{lo} – {hi} з ПДВ 19 %",
  days="Робочий час прибл.", daysUnit="днів художника", designRow="Ескіз (10 %)", discRow="Знижка за культуру/видимість", uaRow="Підтримка України (10 %)", minRow="Мінімальне замовлення",
  design_note="Оплата: 10 % передоплати за ескізи (без повернення, частина бюджету), 50 % після затвердження ескізів, 40 % після завершення.",
  payRows=["Передоплата за ескіз (10 %)", "Після затвердження (50 %)", "Після завершення (40 %)"], hiphopRow="Хіп-хоп-проєкт: можливо й менше 1000 €", mail="або надіслати e-mail",
  disclaimer="Орієнтовна ціна без зобов'язань, з матеріалами. Фіксовану ціну ви отримаєте після виїзду на місце.",
  beta=("Важливо", "Наш калькулятор ще навчається і розвивається – це бета-версія. Розраховані суми можуть суттєво відрізнятися від реальних цін. Ми активно над ним працюємо і незабаром самі покладатимемося на результати цього калькулятора. Дякуємо за розуміння."),
  cta="Надіслати запит з орієнтиром",
  stop_t="На жаль, таке ми не робимо.", stop_p="Розпис лише туалету ми не беремо. Якщо плануєте інші приміщення чи поверхні, оберіть інший варіант вище.",
  briefTitle="Запит із калькулятора ціни", briefPrice="Орієнтир",
  faq=[("Скільки коштує графіті за квадратний метр?", "Фіксованої ціни за квадратний метр немає. Найважливіші – деталізація, висота, поверхня й термін: графічні мотиви значно дешевші за фотореалізм. Калькулятор покаже орієнтир для вашого проєкту."),
       ("Чи є ціна в калькуляторі остаточною?", "Ні, це орієнтир. Після виїзду на місце ви отримаєте фіксовану пропозицію."),
       ("Що входить у ціну?", "Робочий час, фарби (Caparol, Montana Colors) і дорога. Риштування чи автовишка узгоджуються окремо за потреби."),
       ("Як відбувається оплата?", "10 % бюджету – передоплата за ескізи: без повернення, але входить у загальну ціну. 50 % після затвердження ескізів, 40 % після завершення. Усі ціни без ПДВ 19 %."),
       ("Чи є мінімальне замовлення?", "Так, 1000 € нетто. Для проєктів, пов'язаних із хіп-хопом, робимо винятки – тоді можна й менше.")],
  teaser_t="Скільки коштує розпис Вашої стіни?", teaser_p="Площа, мотив, термін – орієнтир за 30 секунд. Без зобов'язань.", teaser_a="До калькулятора",
),
}
