L = dict(
  lang='en', locale='en_US', form=411,
  menu=[('home', 'Home'), ('#leistungen', 'Services'), ('projects', 'Projects'), ('about', 'About Slavik'), ('opening', 'Opening package'), ('#presse', 'Press'), ('magazine', 'Magazine'), ('#kontakt', 'Contact')],
  menu_label='Open menu', close_label='Close menu',
  bubble='Hi, I’m Slavik! Is your wall next?', bubble_call='Call',

  meta_home=('Graffiti Artist & Murals in Frankfurt | Farbaholix',
             'Murals, graffiti and wall design in Frankfurt – for facades, offices, restaurants and sports venues. 20+ years, 1,000+ projects. Get in touch!'),
  tagline='We are here to create!',
  h1='Graffiti Artist & Mural Painting in Frankfurt',
  lead='Farbaholix is a movement – we have been giving walls style for over 20 years. 1,000+ projects delivered.',
  org_desc='Farbaholix designs facades, interiors and events with graffiti and murals – for more than 20 years and over 1,000 projects.',
  cta1='Request a project', cta2='See our work',
  proud='Proudly representing', trust=['20+ years of experience', '1,000+ projects', 'Partner of Montana Colors & Caparol', 'The best materials for the best results'],
  s_services='Services',
  services=[
    ('Murals & facades', 'Large-scale murals for facades, walls and stadiums – in your brand’s style or as free art. The bigger the wall, the better.'),
    ('Interior design', 'Walls and ceilings for offices, restaurants, hotels, clubs and kids’ rooms – from subtle patterns to a UV neon world.'),
    ('Hip-hop & graffiti workshops', 'For teams, schools and kids: graffiti, DJing, b-boying and MCing. In German, English, Ukrainian and Russian.'),
    ('Objects & lettering', 'Custom sneakers, bikes, chalkboards, café menus, canvases, calligraphy and wildstyle.'),
  ],
  stats=[('20+', 'years on the wall'), ('1,000+', 'projects'), ('2,500 m²', 'largest single surface')],
  services_short=['Big walls for brands, cities and stadiums.', 'Offices, restaurants, clubs – all the way to UV neon.', 'Graffiti, DJing, b-boying, MCing – for teams and kids.', 'Lettering, sneakers, bikes, chalkboards, calligraphy.'],
  promo_short='Concept, wall and event from one source.',
  svc_more='Swipe for more',
  go_title='All works', go_all='All', tile_more='See works',
  form_t='Send a message', form_lead='A real person reads every message – usually you get an answer the same day.',
  f_name='Your name', f_contact='E-mail or phone *', f_msg='What’s it about? Wall, place, idea … *', f_send='Send message', f_sending='Sending …',
  f_ok='Thank you! Your message has arrived – I’ll get back to you shortly.', f_err='Sorry, that didn’t work. Please write to me directly by e-mail or WhatsApp.',
  f_att='Attach a photo of the wall', f_att_sub='or a sketch, idea, inspiration · up to 4 images', f_att_bad='Images only (JPG, PNG, WebP, HEIC) – this file was not attached.', f_att_max='Up to 4 images.', f_att_rm='Remove image',
  ch_name='Nice to meet you, {n}!', ch_contact='Perfect – that’s how I’ll reach you.', ch_msg='Sounds exciting!', ch_img='A photo says more than 1000 words 👌', ch_ready='All set – just hit send.',
  f_consent='By sending, you agree that your details are processed to handle your enquiry ({ds}).', f_ds='privacy policy',
  direct_t='Prefer to write directly?', direct_wa='WhatsApp', direct_mail='E-mail', direct_tg='Telegram', insta_sub='New walls, process and backstage – follow us', insta_more='More on Instagram', th_you='You', th_me='Slavik', th_wait='Slavik will answer right here in the chat – maybe right now. Wait about 15 seconds: usually that’s enough to get in direct contact right here on the website.', th_mail=' You will also get it by e-mail.', th_ph='Add something …', th_send='Send', th_new='New enquiry', direct_hello='Hi Slavik, ',
  fab_label='Send Slavik a message', bubble_write='Write',
  promo_t='Opening package', promo_p='Opening soon or planning a new project? Concept, wall design and opening event from one source – at the best price.', promo_a='Learn more',
  s_projects='Recent projects', all_projects='See all projects',
  cases={
    'georgen': ('100 years of Sankt Georgen – botanical mural', 'For the 100th anniversary of Sankt Georgen University in Frankfurt, a grey campus wall became a blooming gallery: bird-of-paradise flowers, monstera, lotus and banana leaves along its entire length. According to the university, the motifs refer to “processes of growth, differentiation and continuous change”.', ['Frankfurt am Main', 'October 2025 – 2026', 'Montana Colors & Caparol']),
    'fsv': ('FSV Frankfurt 1899 – stadium design', 'Over one and a half years, Slavik gave FSV Frankfurt’s stadium at Bornheimer Hang its artistic look: the facade with the club lettering and a crest of about six by four metres, the fan shop, interiors and corridors – in time for the club’s 125th anniversary.', ['Frankfurt am Main', 'Facade & interiors', '1.5-year project']),
    'braubach': ('Braubachstraße – graffiti for peace and freedom', 'For German Unity Day 2025, Slavik painted the windows of six shops on Braubachstraße: “Berlin will live and the wall will fall!” (Willy Brandt), “Woman, Life, Freedom” and “Democracy thrives on taking part” – calligraphy and spray paint under the motto “We protect our democracy”.', ['Frankfurt, Braubachstraße', 'October 2025', 'German Unity Day']),
    'wellen': ('Restaurant Wellenlänge – complete concept', 'One restaurant in Rüsselsheim, one signature: a facade mural with waves and doves, a portrait at the entrance, ornamental walls in the chef’s table area and “Welcome” wings on the gate as a photo spot for guests.', ['Rüsselsheim am Main', 'Facade, interior, photo spot', 'Hospitality']),
    'cansativa': ('Cansativa Group – office lettering', 'For the Frankfurt pharmaceutical company Cansativa, Slavik hand-painted the brand lettering and company milestones on the office walls – clean, straightforward and exactly on brand.', ['Frankfurt am Main', 'Office / corporate design', 'Hand lettering']),
    'enso': ('ENSO Neu-Isenburg – a mural on the theme of “air”', 'For Offenbach district’s project “People, Nature, Togetherness – ENSO”, part of World Design Capital Frankfurt Rhine-Main 2026, Slavik painted a large mural on the theme of “air” on Alicestraße in Neu-Isenburg – based on a design by Miruna Costa, the project’s artistic director. The work carries the motto “Another World Is Possible”. The Offenbach-Post featured it on its front page on 26 September 2026.', ['Neu-Isenburg, Alicestraße', 'Design: Miruna Costa', 'World Design Capital 2026']),
  },
  s_gallery='More work',
  s_voices='What our clients say', translated='Translation',
  s_partners='Partners & clients', partners_alt='Logos of Farbaholix partners and clients, including Caparol, Montana Colors, FSV Frankfurt, Sankt Georgen, Cansativa, Red Bull, adidas and TUI',
  s_press='In the media', press_more='Read article', press_project='See project',
  s_process='How we work',
  steps=[('Enquiry & site visit', 'We look at the surface and listen.'), ('Sketch & colour concept', 'Matched to your brand and your space.'), ('Execution', 'On schedule, in any weather, on any surface.'), ('Handover', 'With photos of the process for your channels.')],
  s_about='About Farbaholix',
  about='Farbaholix is the mural and graffiti studio of Viacheslav “Slavik” Balabaiev in Frankfurt am Main. The Ukrainian artist has been painting since 2004 and has lived in Frankfurt since 2022. He works with brushes, airbrush, spray cans and paint sprayers, supported by AI, AR/VR headsets and lasers for precise layouts. The team also includes Maik Füller – together they create murals, custom sneakers and graffiti workshops. As a partner of Montana Colors and Caparol, Farbaholix uses materials straight from the manufacturer.',
  about_more='More about Slavik',
  s_faq='Frequently asked questions',
  faq=[
    ('How much does a mural cost?', 'The price depends on size, motif and surface. After a site visit you receive a binding fixed-price quote.'),
    ('How long does a project take?', 'It depends on size and motif – you get the exact schedule with the quote. Large projects such as the FSV Frankfurt stadium can run over several months.'),
    ('Can you apply our corporate design?', 'Yes. We bring your company’s logo, colours and style onto the wall – from the reception area to the facade.'),
    ('Do you work outside Frankfurt?', 'Yes, across the Rhine-Main region – for example in Neu-Isenburg, Rüsselsheim and Darmstadt. Projects further away on request.'),
    ('Which languages are workshops held in?', 'German, English, Ukrainian and Russian.'),
    ("Farbaholix or Farbaholics – how is the name spelled?", "Farbaholix – from the German “Farbe” (paint) and “-aholic”: addicted to paint. The logo reading “Farbaholix – Frankfurt Mural Movement” is signed on our walls in Frankfurt and the Rhine-Main area. If you searched for “Farbaholics”, “Farbaholic” or “Mural Movement”, you are in the right place."),
  ],
  s_contact='Contact', contact_lead='Tell us about your wall – we’ll get back to you quickly.', phone_l='Phone', city='Frankfurt am Main, Germany',

  meta_projects=('Projects: Murals & Graffiti in Frankfurt | Farbaholix',
                 'Selected wall designs: FSV Frankfurt stadium, 100 years of Sankt Georgen, Restaurant Wellenlänge, Cansativa and ENSO in Neu-Isenburg.'),
  p_title='Projects', p_lead='Selected wall designs by Farbaholix – from a campus and a stadium to a restaurant.',

  meta_opening=('Opening Package: Wall Design for New Businesses | Farbaholix',
                'New shop, café or office in Frankfurt? Concept, wall design and opening event from one source – also for designers and agencies. Best price.'),
  o_title='Opening package', o_h1='A fresh start with Farbaholix',
  o_text='We love creating something from scratch. Whether you need us for the creative development of your concept or to bring your designers’ finished sketches to life – or you are designers yourselves working on a new project: get in touch. We will make you the best price.',
  o_inc_t='What it can include',
  o_inc=['Facade, logo wall or shop window – so people find you from the street', 'An accent wall in your brand’s style – a photo spot for guests and social media', 'Hand-made chalkboards, menus, signs and lettering', 'Live painting or a graffiti workshop on opening day', 'Photos of the process for your channels'],
  o_works='Made for businesses', o_cta='Discuss your project',

  meta_about=('Slavik (Viacheslav Balabaiev) – Graffiti Artist in Frankfurt',
              'Viacheslav “Slavik” Balabaiev: Ukrainian graffiti and mural artist from Mykolaiv, in Frankfurt since 2022. FSV stadium, Sankt Georgen, 1,000+ commissions.'),
  a_kicker='About Slavik',
  a_h1='Slavik – Viacheslav Balabaiev, graffiti artist in Frankfurt',
  a_lead='Viacheslav “Slavik” Balabaiev is a Ukrainian graffiti and mural artist and the founder of Farbaholix. He has been painting since 2004, has lived in Frankfurt am Main since 2022 and has completed more than 1,000 commissions – including the FSV Frankfurt stadium at Bornheimer Hang and the botanical mural for the 100th anniversary of Sankt Georgen University.',
  a_facts=[('Name', 'Viacheslav “Slavik” Balabaiev'), ('From', 'Mykolaiv, Ukraine'), ('Painting since', '2004'), ('In Frankfurt since', '2022'), ('Projects', '1,000+ commissions'), ('Studio', 'Farbaholix, Frankfurt am Main')],
  a_sections=[
    ('From Mykolaiv to Frankfurt',
     ['Slavik started painting graffiti in 2004 in Mykolaiv, southern Ukraine. He comes from hip-hop culture and is known in the scene by his tag “BVB”. From 2007 he supervised the “Dormashina Hall of Fame”, his hometown’s largest graffiti space; in 2009 he founded Ukraine’s first graffiti school and opened his own graffiti shop. He organised festivals, taught as a lecturer, co-founded the hip-hop collective “South Front” and spent around ten years travelling to major hip-hop events across Europe. One of his largest projects in Ukraine is the design of a sports centre covering more than 2,500 m².',
      'In 2021 he created a mural of around 150 m² in Mykolaiv at the corner of Faleievska and Naberezhna streets: ships from the city’s shipbuilding history – including the “Sviatyi Mykolai” – and chess pieces opposite the chess club. The theme is personal: his grandfather ran one of the city’s shipyards for ten years, and his father built aircraft carriers.',
      'Beyond art, Slavik brings experience as an interior designer for commercial and residential spaces, a decorator and a graphic designer – combined with management and marketing, so projects are finished on time and on target. In 2022 he moved to Frankfurt am Main.']),
    ('Work in Frankfurt and Rhine-Main',
     ['At Bornheimer Hang he spent one and a half years designing FSV Frankfurt’s stadium, including a club crest of about six by four metres. Hessischer Rundfunk reported on it; Slavik said: “Ich lebe jetzt hier und möchte diesen Ort schöner machen” (“I live here now and want to make this place more beautiful”).',
      'For German Unity Day 2025 he painted shop windows on Braubachstraße under the motto “We protect our democracy – together for freedom, diversity and solidarity”, as part of Tourismus+Congress GmbH’s “Jazz zum Dritten” event, together with city marketing and the mayor’s office. He combined historical quotes such as Willy Brandt’s “Berlin will live and the wall will fall!” with current issues. Hip-hop, he says, is his language and art is his megaphone.',
      'From October 2025 he painted the campus wall of Sankt Georgen University with a large floral mural for its 100th anniversary, completed in 2026. In 2026 he painted a large mural on the theme of “air” in Neu-Isenburg for Offenbach district’s ENSO project for World Design Capital, based on a design by Miruna Costa – the Offenbach-Post put it on its front page. The two had met at a newcomer festival in Frankfurt.']),
    ('Style and tools',
     ['Slavik works with brushes, airbrush, spray cans and professional paint sprayers – from photorealism, calligraphy and wildstyle to large facades. Modern tools such as AI, AR/VR headsets and lasers help with sketches and precise transfer to the wall. His belief: “When humans became human, they began painting pictures on walls.”']),
  ],
  a_quote='I live here now and want to make this place more beautiful.', a_quote_src='Slavik to Hessischer Rundfunk, 2024',
  a_photos=[('slavik-sankt-georgen-monstera', 'Slavik painting a monstera on the Sankt Georgen campus wall in Frankfurt'),
            ('slavik-graffiti-auto', 'Slavik in front of a graffiti sports car'),
            ('newcomers-reception', 'Slavik at the Newcomers Reception in Frankfurt’s Römer, September 2026')],
  a_timeline_t='Timeline',
  a_timeline=[('2004', 'First graffiti in Mykolaiv'), ('2007', 'Supervises the Dormashina Hall of Fame'), ('2009', 'Founds Ukraine’s first graffiti school'), ('2021', 'Mural on shipyards and chess in Mykolaiv, approx. 150 m²'), ('2022', 'Moves to Frankfurt am Main'), ('2024', 'FSV Frankfurt stadium design – reported by hr'), ('2025', 'Braubachstraße for German Unity Day; start of the Sankt Georgen mural'), ('2026', 'Sankt Georgen mural completed; ENSO mural in Neu-Isenburg – Offenbach-Post front page')],
  a_press_t='Press & sources',
  a_cta='Request a project with Slavik',

  meta_magazine=('Magazine: Graffiti, Murals & Wall Design | Farbaholix',
                 'Know-how on graffiti and murals in Frankfurt: costs, process, street art spots, workshops – from graffiti artist Slavik (Farbaholix).'),
  m_title='Magazine', m_lead='Graffiti, murals and wall design – from practice.', m_read='Read more', m_planned='planned for',

  wa_t='WhatsApp chat', wa_lead='A live expert (not AI) is here: write straight to WhatsApp from this page – I usually reply right away.',
  wa_name='Your name', wa_msg='What’s it about? Wall, place, idea …', wa_send='Send in WhatsApp', wa_hello='Hi Slavik, this is {name}.', wa_from='(sent via farbaholix.de)',
  wa_float='Open WhatsApp chat with Slavik', mail_under='Prefer e-mail?', wa_label='WhatsApp', email_label='E-mail',
  call_role='Graffiti artist & founder of Farbaholix', call_on='Available now', call_off='In the studio right now – send me a message, I’ll call back',
  call_hook='No call centre, no salesperson: you talk directly to the artist who designed FSV Frankfurt’s stadium.',
  call_btn='Call the artist', call_micro='Two minutes are enough – for a first idea and an honest price range.',
  footer_imp='Legal notice', footer_ds='Privacy',
  logo_alt='Farbaholix – Frankfurt Mural Movement logo',
  breadcrumb_home='Home',
)
