L = dict(
  lang='de', locale='de_DE', form=59,
  menu=[('home', 'Startseite'), ('#leistungen', 'Leistungen'), ('projects', 'Projekte'), ('about', 'Über Slavik'), ('opening', 'Eröffnungspaket'), ('#presse', 'Presse'), ('magazine', 'Magazin'), ('#kontakt', 'Kontakt')],
  menu_label='Menü öffnen', close_label='Menü schließen',
  bubble='Hallo, ich bin Slavik! Ist deine Wand die nächste?', bubble_call='Anrufen',

  # ---------- home ----------
  meta_home=('Graffiti & Wandgestaltung Frankfurt | Farbaholix',
             'Murals, Graffiti & Wandgestaltung in Frankfurt – für Fassaden, Büros, Gastronomie und Sportstätten. 20+ Jahre, 1.000+ Projekte. Jetzt anfragen!'),
  tagline='Wir sind hier, um zu kreieren!',
  h1='Graffiti-Künstler & Wandgestaltung in Frankfurt',
  lead='Farbaholix gestaltet Fassaden, Innenräume und Events mit Graffiti und Murals – seit über 20 Jahren, mit mehr als 1.000 Projekten.',
  cta1='Projekt anfragen', cta2='Arbeiten ansehen',
  trust=['20+ Jahre Erfahrung', '1.000+ Projekte', 'Partner von Montana Colors & Caparol', 'Referenzen: FSV Frankfurt, Sankt Georgen'],
  s_services='Leistungen',
  services=[
    ('Murals & Fassaden', 'Großflächige Wandbilder für Fassaden, Mauern und Stadien – im Stil Ihrer Marke oder als freie Kunst. Je größer die Wand, desto besser.'),
    ('Innenraumgestaltung', 'Wände und Decken für Büros, Restaurants, Hotels, Clubs und Kinderzimmer – vom dezenten Muster bis zur UV-Neonwelt.'),
    ('Hip-Hop- & Graffiti-Workshops', 'Für Teams, Schulen und Kinder: Graffiti, DJing, B-Boying und MCing. Auf Deutsch, Englisch, Ukrainisch und Russisch.'),
    ('Objekte & Lettering', 'Custom Sneakers, Fahrräder, Kreidetafeln, Café-Menüs, Leinwände, Kalligrafie und Wildstyle.'),
  ],
  stats=[('20+', 'Jahre an der Wand'), ('1.000+', 'Projekte'), ('2.500 m²', 'größte Einzelfläche')],
  services_short=['Große Wände für Marken, Städte und Stadien.', 'Büros, Restaurants, Clubs – bis zur UV-Neonwelt.', 'Graffiti, DJing, B-Boying, MCing – für Teams und Kids.', 'Lettering, Sneaker, Bikes, Tafeln, Kalligrafie.'],
  promo_short='Konzept, Wand und Event aus einer Hand.',
  svc_more='Wischen für mehr',
  promo_t='Eröffnungspaket', promo_p='Sie eröffnen bald oder planen ein neues Projekt? Konzept, Wandgestaltung und Eröffnungs-Event aus einer Hand – zum besten Preis.', promo_a='Mehr erfahren',
  s_projects='Ausgewählte Projekte', all_projects='Alle Projekte ansehen',
  cases={
    'georgen': ('100 Jahre Sankt Georgen – botanisches Mural', 'Zum 100-jährigen Jubiläum der Hochschule Sankt Georgen in Frankfurt wurde aus einer grauen Campusmauer eine blühende Galerie: Strelitzien, Monstera, Lotus und Bananenblätter über die gesamte Länge der Mauer. Die Motive verweisen – so die Hochschule – „auf Prozesse des Wachsens, der Differenzierung und der fortlaufenden Veränderung“.', ['Frankfurt am Main', 'seit Oktober 2025', 'Montana Colors & Caparol']),
    'fsv': ('FSV Frankfurt 1899 – Stadiongestaltung', 'Über anderthalb Jahre hat Slavik das Stadion des FSV Frankfurt am Bornheimer Hang künstlerisch gestaltet: die Fassade mit Vereinsschriftzug und rund sechs mal vier Meter großem Wappen, den Fanshop sowie Innenräume und Gänge – passend zum 125-jährigen Vereinsjubiläum.', ['Frankfurt am Main', 'Fassade & Innenräume', '1,5 Jahre Projektlaufzeit']),
    'wellen': ('Restaurant Wellenlänge – Gesamtkonzept', 'Ein Restaurant in Rüsselsheim, eine Handschrift: Fassaden-Mural mit Wellen und Tauben, ein Porträt am Eingang, ornamentale Wände im Chef’s-Table-Bereich und ein „Welcome“-Flügelmotiv am Tor als Fotospot für Gäste.', ['Rüsselsheim am Main', 'Fassade, Interieur, Fotospot', 'Gastronomie']),
    'cansativa': ('Cansativa Group – Lettering im Büro', 'Für das Frankfurter Pharmaunternehmen Cansativa hat Slavik Markenschriftzug und Meilensteine des Unternehmens von Hand an die Bürowände gebracht – klar, geradlinig und exakt im Corporate Design.', ['Frankfurt am Main', 'Büro / Corporate Design', 'Handlettering']),
    'enso': ('ENSO Neu-Isenburg – Wandbild zum Thema „Luft“', 'Für das Projekt „Mensch, Natur, Zusammenhalt – ENSO“ des Kreises Offenbach zur World Design Capital Frankfurt Rhein-Main 2026 hat Slavik in der Alicestraße in Neu-Isenburg ein großes Wandgemälde zum Thema „Luft“ umgesetzt – nach einem Entwurf von Miruna Costa, der künstlerischen Leiterin des Projekts. Das Werk steht unter dem Motto „Another World Is Possible“. Die Offenbach-Post zeigte es am 26.09.2026 auf der Titelseite.', ['Neu-Isenburg, Alicestraße', 'Entwurf: Miruna Costa', 'World Design Capital 2026']),
  },
  s_gallery='Weitere Arbeiten',
  s_voices='Das sagen unsere Kunden', translated=None,
  s_partners='Partner & Kunden', partners_alt='Logos von Partnern und Kunden von Farbaholix, darunter Caparol, Montana Colors, FSV Frankfurt, Sankt Georgen, Cansativa, Red Bull, adidas und TUI',
  s_press='In den Medien', press_more='Artikel lesen', press_project='Zum Projekt',
  s_process='So arbeiten wir',
  steps=[('Anfrage & Vor-Ort-Termin', 'Wir sehen uns die Fläche an und hören zu.'), ('Skizze & Farbkonzept', 'Passend zu Ihrer Marke und Ihrem Raum.'), ('Umsetzung', 'Termingerecht, bei jedem Wetter, auf jedem Untergrund.'), ('Übergabe', 'Mit Fotos vom Entstehungsprozess für Ihre Kanäle.')],
  s_about='Über Farbaholix',
  about='Farbaholix ist das Mural- und Graffiti-Studio von Viacheslav „Slavik“ Balabaiev in Frankfurt am Main. Der ukrainische Künstler malt seit 2004 und lebt seit 2022 in Frankfurt. Er arbeitet mit Pinsel, Airbrush, Sprühdose und Farbspritzgerät, unterstützt von KI, AR/VR-Brillen und Laser für präzise Entwürfe. Als Partner von Montana Colors und Caparol arbeitet Farbaholix mit Materialien direkt vom Hersteller.',
  about_more='Mehr über Slavik',
  s_faq='Häufige Fragen',
  faq=[
    ('Was kostet ein Mural?', 'Der Preis hängt von Fläche, Motiv und Untergrund ab. Nach einem Vor-Ort-Termin erhalten Sie ein verbindliches Festpreisangebot.'),
    ('Wie lange dauert ein Projekt?', 'Das hängt von Fläche und Motiv ab – den genauen Zeitplan erhalten Sie mit dem Angebot. Große Projekte wie das Stadion des FSV Frankfurt laufen auch über mehrere Monate.'),
    ('Können Sie unser Corporate Design umsetzen?', 'Ja. Wir übertragen Logo, Farben und Stil Ihres Unternehmens auf die Wand – vom Empfangsbereich bis zur Fassade.'),
    ('Arbeiten Sie auch außerhalb von Frankfurt?', 'Ja, im gesamten Rhein-Main-Gebiet – zum Beispiel in Neu-Isenburg, Rüsselsheim und Darmstadt. Projekte weiter weg auf Anfrage.'),
    ('In welchen Sprachen finden Workshops statt?', 'Auf Deutsch, Englisch, Ukrainisch und Russisch.'),
  ],
  s_contact='Kontakt', contact_lead='Erzählen Sie uns von Ihrer Wand – wir melden uns schnell zurück.', phone_l='Telefon', city='Frankfurt am Main, Deutschland',

  # ---------- projects ----------
  meta_projects=('Projekte: Murals & Graffiti in Frankfurt | Farbaholix',
                 'Ausgewählte Wandgestaltungen: FSV-Frankfurt-Stadion, 100 Jahre Sankt Georgen, Restaurant Wellenlänge, Cansativa und ENSO in Neu-Isenburg.'),
  p_title='Projekte', p_lead='Ausgewählte Wandgestaltungen von Farbaholix – vom Campus über das Stadion bis zum Restaurant.',

  # ---------- opening ----------
  meta_opening=('Eröffnungspaket: Wandgestaltung für Neueröffnungen | Farbaholix',
                'Neues Geschäft, Café oder Büro in Frankfurt? Konzept, Wandgestaltung und Eröffnungs-Event aus einer Hand – auch für Designer und Agenturen. Bester Preis.'),
  o_title='Eröffnungspaket', o_h1='Neu starten mit Farbaholix',
  o_text='Wir lieben es, etwas von Grund auf neu zu erschaffen. Ob Sie uns für die kreative Entwicklung Ihres Konzepts brauchen oder für die Umsetzung fertiger Entwürfe Ihrer Designer – oder ob Sie selbst Designer sind und an einem neuen Projekt arbeiten: Melden Sie sich bei uns. Wir machen Ihnen den besten Preis.',
  o_inc_t='Das kann dazugehören',
  o_inc=['Fassade, Logo-Wand oder Schaufenster – damit man Sie von der Straße aus findet', 'Eine Akzentwand im Stil Ihrer Marke – als Fotospot für Gäste und Social Media', 'Kreidetafeln, Menüs, Schilder und Lettering in Handarbeit', 'Live-Painting oder Graffiti-Workshop am Eröffnungstag', 'Fotos vom Entstehungsprozess für Ihre Kanäle'],
  o_works='Für Unternehmen gestaltet', o_cta='Projekt besprechen',

  # ---------- about Slavik ----------
  meta_about=('Slavik (Viacheslav Balabaiev) – Graffiti-Künstler in Frankfurt',
              'Viacheslav „Slavik“ Balabaiev: ukrainischer Graffiti- und Mural-Künstler aus Mykolajiw, seit 2022 in Frankfurt. FSV-Stadion, Sankt Georgen, 1.000+ Aufträge.'),
  a_kicker='Über Slavik',
  a_h1='Slavik – Viacheslav Balabaiev, Graffiti-Künstler in Frankfurt',
  a_lead='Viacheslav „Slavik“ Balabaiev ist ein ukrainischer Graffiti- und Mural-Künstler und Gründer von Farbaholix. Er malt seit 2004, lebt seit 2022 in Frankfurt am Main und hat über 1.000 Auftragsarbeiten umgesetzt – darunter die Gestaltung des FSV-Frankfurt-Stadions am Bornheimer Hang und das botanische Mural zum 100. Jubiläum der Hochschule Sankt Georgen.',
  a_facts=[('Name', 'Viacheslav „Slavik“ Balabaiev'), ('Herkunft', 'Mykolajiw, Ukraine'), ('Aktiv seit', '2004'), ('In Frankfurt seit', '2022'), ('Projekte', '1.000+ Auftragsarbeiten'), ('Studio', 'Farbaholix, Frankfurt am Main')],
  a_sections=[
    ('Aus Mykolajiw nach Frankfurt',
     ['Slavik begann 2004 in Mykolajiw im Süden der Ukraine mit Graffiti. Er kommt aus der Hip-Hop-Kultur und ist in der Szene unter seinem Tag „BVB“ bekannt. Ab 2007 betreute er die „Dormashina Hall of Fame“, die größte Graffiti-Fläche seiner Heimatstadt, 2009 gründete er die erste Graffiti-Schule der Ukraine und eröffnete einen eigenen Graffiti-Shop. Er organisierte Festivals, unterrichtete als Dozent, war Mitgründer des Hip-Hop-Kollektivs „South Front“ und reiste rund zehn Jahre lang zu großen Hip-Hop-Events in ganz Europa. Eines seiner größten Projekte in der Ukraine ist die Gestaltung eines Sportzentrums auf mehr als 2.500 m².',
      '2021 entwarf er in Mykolajiw ein rund 150 m² großes Wandbild an der Ecke Falijewska-/Nabereschna-Straße: Schiffe aus der Werftgeschichte der Stadt – darunter die „Swjatyj Mykolaj“ – und Schachfiguren gegenüber dem Schachklub. Das Motiv ist persönlich: Sein Großvater leitete zehn Jahre lang eine der Werften der Stadt, sein Vater baute Flugzeugträger.',
      'Neben der Kunst bringt Slavik Erfahrung als Innenarchitekt für Gewerbe und Wohnen, Dekorateur und Grafikdesigner mit – und verbindet sie mit Management und Marketing, damit Projekte pünktlich und zielgenau fertig werden. 2022 zog er nach Frankfurt am Main.']),
    ('Arbeiten in Frankfurt und Rhein-Main',
     ['Am Bornheimer Hang gestaltete er über anderthalb Jahre das Stadion des FSV Frankfurt, unter anderem mit einem rund sechs mal vier Meter großen Vereinswappen. Der Hessische Rundfunk berichtete darüber; Slavik sagte: „Ich lebe jetzt hier und möchte diesen Ort schöner machen.“',
      'Zum Tag der Deutschen Einheit 2025 bemalte er Schaufenster in der Braubachstraße unter dem Motto „Wir schützen unsere Demokratie – gemeinsam für Freiheit, Vielfalt und Zusammenhalt“, im Rahmen der Aktion „Jazz zum Dritten“ der Tourismus+Congress GmbH, gemeinsam mit dem Stadtmarketing und dem Büro der Bürgermeisterin. Dabei verband er historische Zitate wie Willy Brandts „Berlin wird leben und die Mauer wird fallen!“ mit aktuellen Themen. Hip-Hop, sagt er, sei seine Sprache und die Kunst sein Megafon.',
      'Seit Oktober 2025 gestaltet er die Campusmauer der Hochschule Sankt Georgen mit einem großformatigen Blumen-Mural zum 100-jährigen Jubiläum. 2026 setzte er in Neu-Isenburg für das ENSO-Projekt des Kreises Offenbach zur World Design Capital ein großes Wandgemälde zum Thema „Luft“ nach einem Entwurf von Miruna Costa um – die Offenbach-Post zeigte es auf der Titelseite. Kennengelernt hatten sich die beiden bei einem Newcomer-Festival in Frankfurt.']),
    ('Stil und Werkzeuge',
     ['Slavik arbeitet mit Pinsel, Airbrush, Sprühdose und professionellen Farbspritzgeräten – von Fotorealismus über Kalligrafie und Wildstyle bis zu großflächigen Fassaden. Moderne Werkzeuge wie KI, AR/VR-Brillen und Laser nutzt er für Entwürfe und präzises Übertragen auf die Wand. Seine Überzeugung: „Als der Mensch Mensch wurde, fing er an, Bilder an Wände zu malen.“']),
  ],
  a_quote='Ich lebe jetzt hier und möchte diesen Ort schöner machen.', a_quote_src='Slavik gegenüber dem Hessischen Rundfunk, 2024',
  a_photos=[('slavik-sankt-georgen-monstera', 'Slavik malt eine Monstera an der Campusmauer von Sankt Georgen in Frankfurt'),
            ('slavik-graffiti-auto', 'Slavik vor einem Graffiti mit Sportwagen'),
            ('newcomers-reception', 'Slavik bei der Newcomers Reception im Frankfurter Römer, September 2026')],
  a_timeline_t='Chronik',
  a_timeline=[('2004', 'Erste Graffiti in Mykolajiw'), ('2007', 'Betreut die Dormashina Hall of Fame'), ('2009', 'Gründet die erste Graffiti-Schule der Ukraine'), ('2021', 'Mural über Werften und Schach in Mykolajiw, ca. 150 m²'), ('2022', 'Umzug nach Frankfurt am Main'), ('2024', 'Stadiongestaltung FSV Frankfurt – Bericht im hr'), ('2025', 'Braubachstraße zum Tag der Deutschen Einheit; Start am Sankt-Georgen-Mural'), ('2026', 'ENSO-Wandbild in Neu-Isenburg – Titelseite der Offenbach-Post')],
  a_press_t='Presse & Quellen',
  a_cta='Projekt mit Slavik anfragen',

  # ---------- magazine ----------
  meta_magazine=('Magazin: Graffiti, Murals & Wandgestaltung | Farbaholix',
                 'Wissen rund um Graffiti und Murals in Frankfurt: Kosten, Ablauf, Street-Art-Orte, Workshops – vom Graffiti-Künstler Slavik (Farbaholix).'),
  m_title='Magazin', m_lead='Wissen rund um Graffiti, Murals und Wandgestaltung – aus der Praxis.', m_read='Weiterlesen', m_planned='geplant für',

  wa_t='WhatsApp-Chat', wa_lead='Live-Experte (keine KI) ist erreichbar: Schreib von hier direkt in WhatsApp – meistens antworte ich sofort.',
  wa_name='Dein Name', wa_msg='Worum geht es? Wand, Ort, Idee …', wa_send='In WhatsApp senden', wa_hello='Hallo Slavik, hier ist {name}.', wa_from='(gesendet über farbaholix.de)',
  wa_float='WhatsApp-Chat mit Slavik öffnen', mail_under='Lieber per E-Mail?', wa_label='WhatsApp', email_label='E-Mail',
  call_role='Graffiti-Künstler & Gründer von Farbaholix', call_on='Jetzt erreichbar', call_off='Gerade im Atelier – schreib per WhatsApp, ich rufe zurück',
  call_hook='Kein Callcenter, kein Verkäufer: Du sprichst direkt mit dem Künstler, der das Stadion des FSV Frankfurt gestaltet hat.',
  call_btn='Den Künstler anrufen', call_micro='2 Minuten reichen – für eine erste Idee und einen ehrlichen Preisrahmen.',
  footer_imp='Impressum', footer_ds='Datenschutz',
  logo_alt='Farbaholix – Frankfurt Mural Movement Logo',
  breadcrumb_home='Startseite',
)
