# Works cut from the portfolio PDF (Oct 2026) that were not in the gallery yet.
# key = crop name in scratchpad (page_box); media key = 'pf-' + key; cat: facade / indoor / objects
PF = [
 ('p2_00', 'indoor', 'Schwarz-weißes Frauenporträt mit Afro im Foyer', 'Black-and-white portrait of a woman with an afro in a foyer', 'Чорно-білий портрет жінки з афро у фоє'),
 ('p2_02', 'indoor', 'UV-Bärenfigur im Neonlicht einer Lounge', 'UV bear figure glowing in a lounge', 'УФ-фігура ведмедя в неоновому світлі лаунжу'),
 ('p2_03', 'indoor', 'Farbenfrohes Wandbild mit Ganesha und drei Gesichtern', 'Colourful mural with Ganesha and three faces', 'Яскравий розпис із Ганешею та трьома обличчями'),
 ('p2_04', 'indoor', 'Frauenprofil mit Hut, Schwarz-Weiß in einer Billard-Lounge', 'Woman in a hat, black-and-white profile in a billiards lounge', 'Профіль жінки в капелюсі, чорно-білий розпис у більярдній'),
 ('p2_07', 'indoor', 'Barwand mit Flammen und Whiskeyflasche', 'Bar wall with flames and a whiskey bottle', 'Стіна бару з полум’ям і пляшкою віскі'),
 ('p3_04', 'facade', 'Frauenporträt am Eingang des Restaurants Wellenlänge', 'Portrait of a woman at the entrance of Restaurant Wellenlänge', 'Жіночий портрет біля входу до ресторану Wellenlänge'),
 ('p3_07', 'facade', 'Fotospot „Welcome“ mit Engelsflügeln auf einem Holztor', '“Welcome” photo spot with angel wings on a wooden gate', 'Фотозона «Welcome» з крилами на дерев’яних воротах'),
 ('p4_00', 'facade', 'Saxofon-Mural an einer Hauswand: „Wir sind hier, um zu kreieren“', 'Saxophone mural on a house wall: “We are here to create”', 'Мурал із саксофоном на торці будинку: «Ми тут, щоб творити»'),
 ('p4_01c', 'indoor', '3D-Illusion: Regenbogen-Spirale kriecht durch die Wand', '3D illusion: a rainbow spring crawling through the wall', '3D-ілюзія: райдужна пружинка проходить крізь стіну'),
 ('p4_02', 'facade', 'Hellgrüne Fassade mit geometrischen Flächen', 'Bright green facade with geometric shapes', 'Яскраво-зелений фасад із геометричними площинами'),
 ('p4_03', 'indoor', 'Kugeln in Regenbogenfarben auf einer 3D-Wandverkleidung', 'Rainbow dots on a 3D wall panel', 'Кульки в кольорах веселки на 3D-панелях стіни'),
 ('p4_04', 'indoor', 'Spielraum mit bunten geometrischen Flächen', 'Playroom with colourful geometric planes', 'Ігрова кімната з кольоровими геометричними площинами'),
 ('p5_01', 'facade', 'Adler-Emblem an der Giebelwand eines Wohnhauses', 'Eagle emblem on the gable wall of a house', 'Емблема з орлом на фронтоні житлового будинку'),
 ('p5_02', 'facade', 'Autowerkstatt-Fassade „Autoservice“ in Grau und Blau', 'Car workshop facade “Autoservice” in grey and blue', 'Фасад автосервісу «Autoservice» у сіро-синіх тонах'),
 ('p5_07', 'indoor', 'Schwarzer Geländewagen auf rosa-blauem Verlauf', 'Black off-roader on a pink-blue gradient', 'Чорний позашляховик на рожево-блакитному тлі'),
 ('p5_08', 'indoor', 'Schriftzug „Barber Kids“ im Kinder-Friseursalon', '“Barber Kids” lettering in a children’s barbershop', 'Напис «Barber Kids» у дитячій перукарні'),
 ('p5_09', 'indoor', 'Spielfigur mit Riesenschlüssel in der Reifenwerkstatt', 'Toy figure with a giant spanner in a tyre workshop', 'Фігурка з величезним ключем у шиномонтажі'),
 ('p6_00', 'indoor', 'Lasertag-Arena unter UV-Licht, Gesamtansicht', 'Laser tag arena under UV light, overview', 'Лазертаг-арена в УФ-світлі, загальний вигляд'),
 ('p6_01', 'indoor', 'Lasertag: Galaxie-Wirbel auf den Trennwänden', 'Laser tag: galaxy swirls on the partitions', 'Лазертаг: галактичні вихори на перегородках'),
 ('p6_02', 'indoor', 'Lasertag: leuchtendes Skelett und Planeten', 'Laser tag: glowing skeleton and planets', 'Лазертаг: світний скелет і планети'),
 ('p7_00', 'facade', 'Rolltor „Say wow“ mit Porträt an einer Bar', '“Say wow” roller shutter with a portrait at a bar', 'Ролета «Say wow» з портретом на барі'),
 ('p7_01', 'indoor', 'Ray Charles in Schwarz-Weiß mit Noten', 'Ray Charles in black and white with music notes', 'Рей Чарльз у чорно-білому з нотами'),
 ('p7_05', 'facade', 'Bühnenwand „lovefamily park“ mit Frankfurter Skyline', '“lovefamily park” stage wall with the Frankfurt skyline', 'Сценічна стіна «lovefamily park» зі скайлайном Франкфурта'),
 ('p7_06', 'facade', 'Abstrakte Farbwellen an einer Mauer', 'Abstract waves of colour on a wall', 'Абстрактні кольорові хвилі на стіні'),
 ('p7_07', 'facade', 'Drohnen und Roboter-Fahrzeug, Graffiti-Wand', 'Drones and a robot vehicle, graffiti wall', 'Дрони й робот-позашляховик, графіті-стіна'),
 ('p7_08', 'indoor', 'Porträt mit Hut in einem Durchgang', 'Portrait in a hat in a passageway', 'Портрет у капелюсі в проході'),
 ('p7_09', 'facade', 'Rolltor eines Cafés mit Erdbeer-Tartelette', 'Café roller shutter with a strawberry tartlet', 'Ролета кав’ярні з полуничним тартом'),
 ('p7_10', 'facade', 'Kosmische Farbwelle mit Mond', 'Cosmic wave of colour with a moon', 'Космічна кольорова хвиля з місяцем'),
 ('p7_11', 'objects', 'Live-Painting: Porträt auf großer Leinwand', 'Live painting: portrait on a large canvas', 'Лайв-пейнтинг: портрет на великому полотні'),
 ('p9_01', 'facade', 'Strandmauer mit Weinglas-Motiv „Französischer Boulevard“', 'Beach wall with a wine glass motif “French Boulevard”', 'Пляжна стіна з келихом вина «Французький бульвар»'),
 ('p9_02', 'facade', 'Mexikaner mit Sombrero und Kaktus, Cartoon-Mural', 'Mexican with sombrero and cactus, cartoon mural', 'Мексиканець у сомбреро з кактусом, мультяшний мурал'),
 ('p9_03', 'indoor', 'Sechs Kawaii-Figuren: Süßigkeiten und Früchte', 'Six kawaii characters: sweets and fruit', 'Шість каваї-персонажів: солодощі й фрукти'),
 ('p9_04', 'indoor', 'Schachfiguren auf einer gewölbten Brett-Kugel, 3D', 'Chess pieces on a curved board sphere, 3D', 'Шахові фігури на випуклій дошці-кулі, 3D'),
 ('p9_06', 'indoor', 'Goofy-Wandbild im Rahmen', 'Goofy mural in a frame', 'Розпис із Гуфі в рамці'),
 ('p9_07', 'indoor', 'Segelschiff im Mondlicht', 'Sailing ship in the moonlight', 'Вітрильник у місячному світлі'),
 ('p14_00', 'facade', 'Aztekische Sonne an einem Kassenhäuschen', 'Aztec sun on a ticket booth', 'Ацтецьке сонце на касовому павільйоні'),
 ('p14_02', 'facade', 'Wasserpark-Fassade „Bananenrepublik“, Panorama', 'Water park facade “Banana Republic”, panorama', 'Фасад аквапарку «Бананова республіка», панорама'),
 ('p15_01', 'indoor', 'Gaming-Club mit Sitzsäcken und Bildschirmwand', 'Gaming club with beanbags and a wall of screens', 'Кіберклуб із кріслами-мішками та стіною екранів'),
 ('p15_02', 'indoor', 'Gamer mit Kapuze, Wandbild im Gaming-Club', 'Hooded gamer, mural in a gaming club', 'Геймер у каптурі, розпис у кіберклубі'),
 ('p15_05', 'indoor', 'Gaming-Club unter UV-Licht, Panorama', 'Gaming club under UV light, panorama', 'Кіберклуб в УФ-світлі, панорама'),
 ('p15_06a', 'indoor', 'Rote Decke mit schwarzem Barock-Ornament', 'Red ceiling with a black baroque ornament', 'Червона стеля з чорним бароковим орнаментом'),
 ('p15_08', 'indoor', 'Spielkarten-Symbole an Decke und Wand', 'Playing-card symbols on ceiling and wall', 'Символи гральних карт на стелі й стіні'),
 ('p16_00', 'indoor', 'Der Pate – Schwarz-Weiß-Porträt', 'The Godfather – black-and-white portrait', 'Хрещений батько – чорно-білий портрет'),
 ('p16_02', 'indoor', 'Einstein-Porträt auf abstrakten Graustufen', 'Einstein portrait on abstract greyscale', 'Портрет Ейнштейна на абстрактному сірому тлі'),
 ('p16_03', 'facade', 'Feuerwehr-Mural an einer Fassade, Mykolajiw', 'Firefighter mural on a facade, Mykolaiv', 'Мурал із пожежником на фасаді, Миколаїв'),
 ('p16_04', 'indoor', 'Film-noir-Figur am Ausgang', 'Film-noir figure by the exit', 'Персонаж у стилі нуар біля виходу'),
 ('p16_06', 'indoor', 'The Notorious B.I.G. – Hip-Hop-Wand', 'The Notorious B.I.G. – hip-hop wall', 'The Notorious B.I.G. – хіп-хоп-стіна'),
 ('p16_07', 'indoor', '„The real hip hop is over here“ – Wand mit Rap-Legenden', '“The real hip hop is over here” – wall of rap legends', '«The real hip hop is over here» – стіна з легендами репу'),
 ('p16_08', 'indoor', 'Tupac und Snoop Dogg, Hip-Hop-Wand', 'Tupac and Snoop Dogg, hip-hop wall', 'Тупак і Снуп Дог, хіп-хоп-стіна'),
 ('p17_00', 'indoor', 'Saxofon in Schwarz-Weiß, Entstehung des Wandbilds', 'Saxophone in black and white, the mural in progress', 'Саксофон у чорно-білому, процес розпису'),
 ('p17_02', 'indoor', 'Food-Court mit Farbspritzern „Ricchi & Poveri“', 'Food court with paint splashes “Ricchi & Poveri”', 'Фудкорт із бризками фарби «Ricchi & Poveri»'),
 ('p18_00', 'indoor', 'Comicfigur „Drunk Patrick“ auf geometrischem Hintergrund', 'Cartoon character “Drunk Patrick” on a geometric background', 'Персонаж «Drunk Patrick» на геометричному тлі'),
 ('p18_01', 'indoor', 'Roter Geländewagen im Gelände, realistisch', 'Red off-roader on rough terrain, realistic', 'Червоний позашляховик на бездоріжжі, реалістично'),
 ('p18_02', 'indoor', 'Fitness-Mural: Athletin mit Hanteln', 'Fitness mural: athlete with dumbbells', 'Фітнес-мурал: спортсменка з гантелями'),
 ('p18_03', 'indoor', 'Pin-up mit Spiralhut auf einem Sprungbrett', 'Pin-up girl with a spiral hat on a diving board', 'Пін-ап дівчина в капелюсі-спіралі на трампліні'),
 ('p18_04', 'indoor', 'Rote Rose „Just beautiful“', 'Red rose “Just beautiful”', 'Червона троянда «Just beautiful»'),
 ('p18_05', 'facade', 'Lippen und Kirschen an einer Säule', 'Lips and cherries on a pillar', 'Губи й вишні на колоні'),
 ('p18_07', 'facade', 'Tor eines Fitnessstudios „Green Club“ mit Gras', 'Fitness studio gate “Green Club” with grass', 'Ворота фітнес-студії «Green Club» із травою'),
 ('p19_00', 'indoor', 'Gasmaske mit leuchtenden Gläsern', 'Gas mask with glowing lenses', 'Протигаз зі світними скельцями'),
 ('p19_01', 'indoor', 'Athlet mit Vorschlaghammer, Bewegungsphasen', 'Athlete with a sledgehammer, motion sequence', 'Атлет із кувалдою, фази руху'),
 ('p19_02', 'facade', 'Tennisspieler an der Fassade von „Tennis Land“', 'Tennis player on the “Tennis Land” facade', 'Тенісист на фасаді «Tennis Land»'),
 ('p19_04', 'indoor', 'Leuchtender Kosmos-Wirbel unter UV-Licht', 'Glowing cosmic vortex under UV light', 'Світний космічний вир в УФ-світлі'),
 ('p19_05', 'facade', 'Superheldin in Rot-Blau-Gold, Mural', 'Superheroine in red, blue and gold, mural', 'Супергероїня в червоно-синьо-золотому, мурал'),
 ('p19_07', 'facade', 'Dunkler Ritter, Superhelden-Mural', 'Dark knight, superhero mural', 'Темний лицар, супергеройський мурал'),
 ('p19_08', 'indoor', 'Fitnessstudio „Classic“ mit Punkte-Welle, Panorama', '“Classic” gym with a dotted wave, panorama', 'Спортзал «Classic» із хвилею з крапок, панорама'),
 ('p19_09', 'indoor', 'Ukrainische Petrykiwka-Blumen an der Wand', 'Ukrainian Petrykivka flowers on the wall', 'Петриківський розпис із квітами на стіні'),
 ('p20_01a', 'objects', 'Graffiti-Piece „One Love“ in Türkis', 'Graffiti piece “One Love” in turquoise', 'Графіті-піс «One Love» у бірюзі'),
 ('p20_01b', 'objects', 'Silber-Rot-Piece an einer Ruine', 'Silver and red piece on a ruin', 'Срібно-червоний піс на руїні'),
 ('p20_02d', 'objects', 'Wildstyle-Piece „Viacheslav“ an einer Hall of Fame', 'Wildstyle piece “Viacheslav” at a hall of fame', 'Вайлдстайл-піс «Viacheslav» на хол-оф-фейм'),
 ('p20_03', 'objects', 'Bubble-Style-Piece in Blau und Lila', 'Bubble-style piece in blue and purple', 'Піс у стилі бабл у синьому й фіолетовому'),
 ('p20_05', 'objects', 'Wildstyle in Rosa und Weinrot unter einer Brücke', 'Wildstyle in pink and burgundy under a bridge', 'Вайлдстайл у рожевому й бордовому під мостом'),
 ('p20_06', 'objects', '„One Love“ – Schrift in Rot auf Gelb', '“One Love” – red lettering on yellow', '«One Love» – червоні літери на жовтому'),
 ('p20_07', 'objects', 'Kalligrafie in gotischen Buchstaben', 'Calligraphy in gothic letters', 'Каліграфія готичними літерами'),
 ('p20_08', 'objects', 'Logo-Lettering „South Bags“', '“South Bags” logo lettering', 'Леттеринг логотипу «South Bags»'),
 ('p20_09', 'objects', 'Buchstabe „S“ auf Leinwand', 'Letter “S” on canvas', 'Літера «S» на полотні'),
 ('p20_10', 'objects', 'Piece „Slavik“ in Grün an einer Hall of Fame', '“Slavik” piece in green at a hall of fame', 'Піс «Slavik» у зеленому на хол-оф-фейм'),
 ('p20_11', 'objects', 'Wildstyle „Slavik“ in Gelb und Pink, Hamburg 2022', '“Slavik” wildstyle in yellow and pink, Hamburg 2022', 'Вайлдстайл «Slavik» у жовтому й рожевому, Гамбург 2022'),
]
