"""Hidden page "smi-bvb": Slavik's public work in Mykolaiv (Ukraine) before moving to Germany, as reported by the media.
Not linked from anywhere, noindex. Full archive copies of the articles live on a separate password-protected page
(page key 'smiarchiv') and as raw HTML + extracted text + images in archive/smi-bvb/ (collected 03.10.2026)."""
import json, os

ARCHIVED = '03.10.2026'
# full texts are kept out of the (public) git repo: archive/ is gitignored; without it only the archive page is skipped
_EXF = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'archive', 'smi-bvb', 'extract.json')
EX = json.load(open(_EXF)) if os.path.exists(_EXF) else None
WAYBACK = 'https://web.archive.org/web/2018/'

UI = {
    'de': dict(title='BVB – Presse und öffentliches Wirken in Mykolajiw', kicker='Medienarchiv · vor dem Umzug nach Deutschland',
               lead='Eine Zusammenstellung aller auffindbaren Medienberichte über Viacheslav „BVB“ Balabaiev aus seiner Heimatstadt Mykolajiw (Ukraine): Graffiti-Kultur, Jugendarbeit, Stadtgestaltung. Jeder Eintrag nennt Quelle, Datum und Originallink. Weil ukrainische Lokalmedien Artikel immer wieder löschen, wurden die Texte und Fotos am %s gesichert.' % ARCHIVED,
               bio_t='Kurzbiografie bis 2022', tl_t='Chronik der Berichte', self_t='BVB über sich selbst', self_src='Selbstporträt im internationalen Graffiti-Verzeichnis Monochronicle (englisch):',
               orig='Originalartikel', arch='Archivkopie (Passwort)', wb='Kopie im Internet Archive', quote='Zitat', status={'ok': 'Text und Fotos lokal gesichert', 'blocked': 'Quelle blockiert automatische Abrufe – nur Link gesichert', 'deleted': 'Artikel gelöscht – nur noch im Internet Archive', 'gone': 'Artikel gelöscht, keine Archivkopie – Inhalt nur aus Suchergebnissen bekannt'},
               photos='Fotos aus den Berichten', credit='Fotos: jeweilige Redaktionen bzw. Fotografen, siehe Quelle.', epi_t='Epilog', orig_lang={'ru': 'Original auf Russisch', 'uk': 'Original auf Ukrainisch', 'en': 'Original auf Englisch'},
               note='Interne Seite – nicht verlinkt und nicht in Suchmaschinen.'),
    'en': dict(title='BVB – press and public work in Mykolaiv', kicker='Media archive · before the move to Germany',
               lead='A compilation of every media report we could find about Viacheslav “BVB” Balabaiev from his home town of Mykolaiv (Ukraine): graffiti culture, youth work, urban design. Each entry gives source, date and the original link. Because Ukrainian local media keep deleting articles, the texts and photos were saved on %s.' % ARCHIVED,
               bio_t='Short biography up to 2022', tl_t='Timeline of reports', self_t='BVB about himself', self_src='Self-portrait in the international graffiti directory Monochronicle:',
               orig='Original article', arch='Archive copy (password)', wb='Copy in the Internet Archive', quote='Quote', status={'ok': 'Text and photos saved locally', 'blocked': 'Source blocks automated access – link saved only', 'deleted': 'Article deleted – only in the Internet Archive', 'gone': 'Article deleted, no archive copy – content known from search results only'},
               photos='Photos from the reports', credit='Photos: the respective newsrooms or photographers, see source.', epi_t='Epilogue', orig_lang={'ru': 'Original in Russian', 'uk': 'Original in Ukrainian', 'en': 'Original in English'},
               note='Internal page – not linked and not indexed by search engines.'),
    'uk': dict(title='BVB – преса і громадська діяльність у Миколаєві', kicker='Медіаархів · до переїзду до Німеччини',
               lead='Добірка всіх знайдених публікацій про В’ячеслава «BVB» Балабаєва з рідного Миколаєва: графіті-культура, робота з молоддю, оформлення міста. Для кожного запису – джерело, дата й посилання на оригінал. Оскільки місцеві медіа видаляють статті, тексти й фото збережено %s.' % ARCHIVED,
               bio_t='Коротка біографія до 2022 року', tl_t='Хроніка публікацій', self_t='BVB про себе', self_src='Автопортрет у міжнародному каталозі графіті-художників Monochronicle (англійською):',
               orig='Оригінал статті', arch='Архівна копія (пароль)', wb='Копія в Internet Archive', quote='Цитата', status={'ok': 'Текст і фото збережено локально', 'blocked': 'Джерело блокує автоматичне завантаження – збережено лише посилання', 'deleted': 'Статтю видалено – є лише в Internet Archive', 'gone': 'Статтю видалено, архівної копії немає – зміст відомий лише з пошукової видачі'},
               photos='Фото з публікацій', credit='Фото: відповідні редакції або фотографи, див. джерело.', epi_t='Епілог', orig_lang={'ru': 'Оригінал російською', 'uk': 'Оригінал українською', 'en': 'Оригінал англійською'},
               note='Внутрішня сторінка – без посилань і без індексації пошуковиками.'),
}

BIO = {
    'de': [('geboren in Mykolajiw', 'Großvater Heorhij Balabaiev leitete zehn Jahre die Werft „61 Kommunarden“, der Vater baute Flugzeugträger auf der Schwarzmeerwerft. Mit sieben Jahren lernte Slavik im Schachklub bei Mykola Schelest Schach und erreichte eine Wertungsklasse.'),
           ('2004', 'erste Graffiti, inspiriert von der Hip-Hop-Kultur; Writer-Name BVB.'),
           ('2005', 'erste Auftragsarbeiten – bis 2022 über 1.000 umgesetzte Projekte.'),
           ('seit 2007', 'Kurator der größten Kunstfläche der Stadt: der „Hall of Fame“ an der Wand des Werks „Dormaschyna“, an der Writer aus Mykolajiw und Kyjiw malten.'),
           ('2009', 'gründet die erste Graffiti-Schule der Ukraine und einen eigenen Graffiti-Shop.'),
           ('2011', 'Galerie-Ausstellung – mit der Erkenntnis, dass sein Raum die Straße und private Interieurs sind.'),
           ('2010er', 'Mitglied der Jugendorganisation „Alter Sport“ (Events, Extremsport, gesunder Lebensstil), Vorträge über Hip-Hop-Kultur, Crew „South Front“ aus Breakdancern, DJs und ihm als Künstler; rund zehn Jahre Reisen zu den großen Hip-Hop-Events Europas.'),
           ('größtes Projekt', 'Sportklub „Excavator“ in Mykolajiw – über 2.500 m² gestaltete Wände.'),
           ('2017', 'Moderator des städtischen Festivals zum Tag der Jugend auf dem Sobornaja-Platz.'),
           ('2019', 'Graffiti „Мы здесь, чтобы творить“ („Wir sind hier, um zu kreieren“) am künftigen Skatepark bei der Sportschule „Nadeschda“.'),
           ('2021', 'Mural mit drei in Mykolajiw gebauten Schiffen und Schachfiguren zum 232. Stadtgeburtstag, Ecke Faleewska/Nabereschna, 150 m².')],
    'en': [('born in Mykolaiv', 'his grandfather Heorhii Balabaiev ran the “61 Communards” shipyard for ten years, his father built aircraft carriers at the Black Sea Shipyard. At seven, Slavik learned chess from Mykola Shelest at the chess club and earned a chess rating class.'),
           ('2004', 'first graffiti, inspired by hip-hop culture; writer name BVB.'),
           ('2005', 'first commissions – more than 1,000 completed projects by 2022.'),
           ('since 2007', 'curator of the city’s largest art space: the “Hall of Fame” on the wall of the Dormashyna plant, where writers from Mykolaiv and Kyiv painted.'),
           ('2009', 'founds Ukraine’s first graffiti school and his own graffiti shop.'),
           ('2011', 'gallery exhibition – and the realisation that his space is the street and private interiors.'),
           ('2010s', 'member of the youth organisation “Alter Sport” (events, extreme sports, healthy lifestyle), talks on hip-hop culture, crew “South Front” of breakdancers, DJs and himself as the artist; around ten years of travelling to Europe’s big hip-hop events.'),
           ('largest project', 'the Excavator sports club in Mykolaiv – more than 2,500 m² of painted walls.'),
           ('2017', 'host of the city’s Youth Day festival on Soborna Square.'),
           ('2019', 'graffiti “Мы здесь, чтобы творить” (“We are here to create”) at the future skate park next to the Nadezhda sports school.'),
           ('2021', 'mural with three ships built in Mykolaiv and chess pieces for the city’s 232nd anniversary, corner of Faleievska/Naberezhna, 150 m².')],
    'uk': [('народився в Миколаєві', 'дід Георгій Матвійович Балабаєв десять років очолював суднобудівний завод імені 61 комунара, батько будував авіаносці на ЧСЗ. У сім років Славік почав займатися шахами в клубі в Миколи Васильовича Шелеста й отримав шаховий розряд.'),
           ('2004', 'перші графіті під впливом хіп-хоп-культури; псевдонім BVB.'),
           ('2005', 'перші комерційні замовлення – до 2022 року понад 1000 реалізованих проєктів.'),
           ('з 2007', 'куратор найбільшого арт-об’єкта міста – Hall of Fame на стіні заводу «Дормашина», де малювали райтери з Миколаєва й Києва.'),
           ('2009', 'засновує першу в Україні школу графіті та власний графіті-шоп.'),
           ('2011', 'галерейна виставка – і висновок, що його простір не музей, а вулиця та приватні інтер’єри.'),
           ('2010-ті', 'учасник молодіжної організації «Альтер-Спорт» (події, екстремальний спорт, здоровий спосіб життя), лекції про хіп-хоп, команда South Front – брейкери, діджеї та він як художник; близько десяти років подорожей на великі хіп-хоп-події Європи.'),
           ('найбільший проєкт', 'спортклуб «Екскаватор» у Миколаєві – понад 2500 м² розписаних стін.'),
           ('2017', 'ведучий міського фестивалю до Дня молоді на Соборній площі.'),
           ('2019', 'графіті «Мы здесь, чтобы творить» («Ми тут, щоб творити») на місці майбутнього скейт-парку біля спортшколи «Надія».'),
           ('2021', 'мурал із трьома збудованими в Миколаєві кораблями та шаховими фігурами до 232-ї річниці міста, ріг Фалеєвської та Набережної, 150 м².')],
}

SELF = {'k': 'monochronicle', 'en': '"My name is Viacheslav Balabaiev, I was born in Mykolayiv, Ukraine. I started writing graffiti in 2004, being inspired by Hip Hop culture. My artworks are represented in t.me/graffitibybvb. Since 2007 I supervise the biggest art object in my native city: Dormashina Hall of fame. In 2009 I created Ukraine\'s first graffiti school, opened my own graffiti shop. For about 10 years I was traveling throw all the Europe, visiting the biggest Hip Hop events. Also, I\'m fond of organizing events, promoting health-positive ways of life, extreme sports, and arts as a member of Alter Sport youth organization. In 2011 I made a gallery exhibition, but found out, that my space is not a museum or gallery, but streets and private interiors. My team - South Front is the connection of Breakdancers, DJ\'s and me as an artist. We represent different cities, mostly: Crimean. Since 2005 I do commercial graffiti. There were more than 1000 projects completed successfully. My biggest project was the Excavator sports club in my native town. More than 2500 square meters of walls became beautiful. Also, I present lectures about Hip Hop, spreading this culture to mass. For the last 8 years, I manage my own furniture company, that called South Bags (southbags.com.ua). We create premium quality beanbags and different other products and sell them worldwide, including EU and USA. For now, I have a goal in life: to visit Miami. I do want to visit Wynwood Walls and create my best mural there, representing my style, my country. My way of doing business: "Stop selling, start helping". I want to inspire other people to think worldwide, put big goals, and deserve them." - BVB.', 'url': 'https://monochronicle.com/artist/bvb/', 'imgs': ['smi-monochronicle-00', 'smi-monochronicle-01', 'smi-monochronicle-02', 'smi-monochronicle-03', 'smi-monochronicle-04', 'smi-monochronicle-05'],
        'tr': {
    'de': '„Mein Name ist Viacheslav Balabaiev, ich wurde in Mykolajiw, Ukraine, geboren. 2004 habe ich angefangen, Graffiti zu schreiben – inspiriert von der Hip-Hop-Kultur. Seit 2007 betreue ich das größte Kunstobjekt meiner Heimatstadt: die Dormaschyna Hall of Fame. 2009 habe ich die erste Graffiti-Schule der Ukraine gegründet und einen eigenen Graffiti-Shop eröffnet. Rund zehn Jahre bin ich durch ganz Europa zu den größten Hip-Hop-Events gereist. Außerdem organisiere ich gern Veranstaltungen und fördere als Mitglied der Jugendorganisation Alter Sport einen gesunden Lebensstil, Extremsport und Kunst. 2011 hatte ich eine Galerie-Ausstellung, habe aber gemerkt: Mein Raum ist nicht das Museum oder die Galerie, sondern die Straße und private Interieurs. Mein Team South Front verbindet Breakdancer, DJs und mich als Künstler. Seit 2005 mache ich Auftrags-Graffiti – mehr als 1.000 Projekte wurden erfolgreich umgesetzt. Mein größtes Projekt war der Sportklub Excavator in meiner Heimatstadt: Über 2.500 Quadratmeter Wand wurden schön. Ich halte auch Vorträge über Hip-Hop und bringe diese Kultur zu vielen Menschen. […] Mein Ziel: Miami besuchen, die Wynwood Walls sehen und dort mein bestes Mural malen – in meinem Stil, für mein Land. Mein Geschäftsprinzip: „Hör auf zu verkaufen, fang an zu helfen.“ Ich möchte andere inspirieren, global zu denken, sich große Ziele zu setzen und sie sich zu verdienen.“',
    'en': None,
    'uk': '«Мене звати В’ячеслав Балабаєв, я народився в Миколаєві. Графіті почав писати у 2004 році під впливом хіп-хоп-культури. З 2007 року курую найбільший арт-об’єкт рідного міста – Hall of Fame на «Дормашині». У 2009 році створив першу в Україні школу графіті й відкрив власний графіті-шоп. Близько десяти років їздив Європою на найбільші хіп-хоп-події. Люблю організовувати заходи й популяризувати здоровий спосіб життя, екстремальний спорт і мистецтво як учасник молодіжної організації «Альтер-Спорт». У 2011 році мав галерейну виставку, але зрозумів: мій простір – не музей і не галерея, а вулиці й приватні інтер’єри. Моя команда South Front – це брейкери, діджеї та я як художник. Із 2005 року займаюся комерційним графіті – понад 1000 успішних проєктів. Найбільший – спортклуб «Екскаватор» у рідному місті: понад 2500 квадратних метрів стін стали красивими. Також читаю лекції про хіп-хоп, поширюючи цю культуру. […] Моя мета – побувати в Маямі, побачити Wynwood Walls і створити там свій найкращий мурал – у своєму стилі, представляючи свою країну. Мій принцип у бізнесі: «Перестань продавати, почни допомагати». Хочу надихати людей мислити глобально, ставити великі цілі й досягати їх».'}}

# timeline: chronological; 'k' = key in extract.json (archived), status: ok / blocked / deleted / gone
ITEMS = [
    dict(id='den-molodi-2017', date='25.06.2017', outlet='Шипшина (shipovnik.ua)', k='2017-06-shipovnik', lang='ru', status='ok', url='https://shipovnik.ua/longrid/16390',
         head='Граффити, BMX и брейк-данс: николаевцы «отожгли» на Дне молодежи (Фоторепортаж)',
         imgs=['smi-2017-06-shipovnik-00', 'smi-2017-06-shipovnik-21', 'smi-2017-06-shipovnik-17'],
         sum={'de': 'Fotoreportage vom städtischen Fest zum Tag der Jugend auf dem Sobornaja-Platz: Fahrradkorso der Organisation „Alter Sport“, Graffiti-Battle, BMX und Breakdance. Viacheslav Balabaiev – „der bekannte Mykolajiwer Writer BVB“ – moderiert das Festival, eröffnet es und kommentiert die Arbeiten der Graffiti-Teams live.',
              'en': 'Photo report from the city’s Youth Day festival on Soborna Square: a bike ride by the “Alter Sport” organisation, a graffiti battle, BMX and breakdance. Viacheslav Balabaiev – “the well-known Mykolaiv writer BVB” – hosts the festival, opens it and comments live on the graffiti teams’ work.',
              'uk': 'Фоторепортаж із міського свята до Дня молоді на Соборній площі: велопробіг організації «Альтер-Спорт», графіті-батл, BMX і брейк-данс. В’ячеслав Балабаєв – «відомий миколаївський райтер BVB» – веде фестиваль, відкриває його й наживо коментує роботи графіті-команд.'},
         quotes=[('Роман развивает свое искусство уже больше десяти лет. Сегодня он пишет слово «Молодость». И каждая буква здесь несет смысл — если бы он писал слово «Шуруповерт», то буквы, уверен, были бы другими.',
                  {'de': 'Roman entwickelt seine Kunst seit über zehn Jahren. Heute schreibt er das Wort „Jugend“. Jeder Buchstabe trägt hier eine Bedeutung – würde er „Akkuschrauber“ schreiben, wären die Buchstaben ganz andere.',
                   'en': 'Roman has been developing his art for more than ten years. Today he is writing the word “Youth”. Every letter here carries meaning – if he were writing “screwdriver”, the letters would be completely different.',
                   'uk': 'Роман розвиває своє мистецтво вже понад десять років. Сьогодні він пише слово «Молодість». І кожна літера тут несе зміст – якби він писав «Шуруповерт», літери, певен, були б інакшими.'})]),
    dict(id='dormashyna-2017', date='2017', outlet='News.pn', k=None, lang='ru', status='blocked', url='https://news.pn/ru/public/189518', wayback='https://web.archive.org/web/20171019134739/https://news.pn/ru/public/189518',
         head='Николаевские и киевские райтеры рисуют новые граффити на стене возле «Дормашины»', imgs=[],
         sum={'de': 'Bericht über eine gemeinsame Aktion von Writern aus Mykolajiw und Kyjiw an der Hall-of-Fame-Wand beim Werk „Dormaschyna“, die BVB seit 2007 kuratiert.',
              'en': 'Report on a joint session of writers from Mykolaiv and Kyiv at the Hall of Fame wall next to the Dormashyna plant, curated by BVB since 2007.',
              'uk': 'Матеріал про спільну роботу миколаївських і київських райтерів на стіні Hall of Fame біля заводу «Дормашина», яку BVB курує з 2007 року.'}, quotes=[]),
    dict(id='dormashyna-niklife', date='2017/2018', outlet='NikLife (niklife.com.ua)', k=None, lang='ru', status='deleted', url='https://niklife.com.ua/citylook/59519', wayback='https://web.archive.org/web/20181205093540/http://niklife.com.ua:80/citylook/59519',
         head='Киево-николаевский микс из райтеров начал «бомбить» стену на «Дормашине»', imgs=[],
         sum={'de': 'Die Wand am Werk „Dormaschyna“ – eine der ungewöhnlichsten Sehenswürdigkeiten Mykolajiws, erstmals 2007 bemalt – wird von einem Kyjiw-Mykolajiw-Mix aus Writern neu gestaltet. Der Artikel wurde auf der Website gelöscht.',
              'en': 'The wall at the Dormashyna plant – one of Mykolaiv’s most unusual sights, first painted in 2007 – is repainted by a Kyiv–Mykolaiv mix of writers. The article has been deleted from the website.',
              'uk': 'Стіну заводу «Дормашина» – одну з найнезвичніших пам’яток Миколаєва, вперше розписану у 2007 році, – оновлює київсько-миколаївський мікс райтерів. Статтю з сайту видалено.'}, quotes=[]),
    dict(id='niklife-muraly', date='—', outlet='NikLife (niklife.com.ua)', k=None, lang='ru', status='gone', url='https://niklife.com.ua/ru/focus/64394', wayback=None,
         head='Почему в Николаеве нет муралов', imgs=[],
         sum={'de': 'Analyse zur fehlenden Mural-Kultur in Mykolajiw. Laut Suchergebnissen wird Viacheslav Balabaiev darin als Anführer der Graffiti-Kultur der Stadt bezeichnet – und als einziger Writer aus Mykolajiw mit Arbeiten auf Wänden in den meisten Ländern Europas.',
              'en': 'Analysis of the missing mural culture in Mykolaiv. According to search results, it calls Viacheslav Balabaiev the leader of the city’s graffiti culture – and the only Mykolaiv writer with work on walls in most European countries.',
              'uk': 'Аналітика про брак муралів у Миколаєві. За пошуковою видачею, В’ячеслава Балабаєва там названо лідером графіті-культури міста – і єдиним миколаївським райтером, чиї роботи є на стінах у більшості країн Європи.'}, quotes=[]),
    dict(id='skatepark-svidok', date='17.09.2019', outlet='Свідок (svidok.info)', k='2019-09-svidok', lang='ru', status='ok', url='https://svidok.info/ru/news/33371',
         head='В Николаеве на месте скейт-парка появилось яркое граффити', imgs=['smi-2019-09-svidok-00', 'smi-2019-09-svidok-02'],
         sum={'de': 'Auf einer Brache bei der Sportschule „Nadeschda“, wo früher eine Eisbahn war, entsteht ein Skatepark für Biker, Skater und Roller. Den Anfang macht BVBs Graffiti „Мы здесь, чтобы творить“ („Wir sind hier, um zu kreieren“). Vitalij Woronow, Leiter der städtischen Entwicklungsagentur, dankt öffentlich.',
              'en': 'On a vacant lot next to the Nadezhda sports school, once an ice rink, a skate park for bikers, skaters and rollers is being created. It starts with BVB’s graffiti “Мы здесь, чтобы творить” (“We are here to create”). Vitalii Voronov, head of the city’s development agency, thanks him publicly.',
              'uk': 'На пустирі біля спортшколи «Надія», де колись був каток, з’являється скейт-парк для велосипедистів, скейтерів і роликерів. Початок – графіті BVB «Мы здесь, чтобы творить» («Ми тут, щоб творити»). Директор Агенції розвитку Миколаєва Віталій Воронов публічно дякує художнику.'},
         quotes=[('Вячеславу Балабаеву за крутую и быструю работу и неповторимые граффити.',
                  {'de': '[Danke] Viacheslav Balabaiev für die starke und schnelle Arbeit und das einzigartige Graffiti. – Vitalij Woronow, Agentur für Entwicklung Mykolajiws',
                   'en': '[Thanks] to Viacheslav Balabaiev for the great, fast work and the unique graffiti. – Vitalii Voronov, Mykolaiv Development Agency',
                   'uk': '[Дякую] В’ячеславу Балабаєву за круту й швидку роботу та неповторні графіті. – Віталій Воронов, Агенція розвитку Миколаєва'})]),
    dict(id='skatepark-vn', date='24.09.2019', outlet='Вечірній Миколаїв (vn.mk.ua)', k='2019-09-vn-skate', lang='ru', status='ok', url='https://vn.mk.ua/ru/skejt-park-vmesto-pustyrya/',
         head='Скейт-парк вместо пустыря', imgs=[],
         sum={'de': 'Die Stadtzeitung nennt die Beteiligten: Organisator Roland Bajrosjan, Künstler Viacheslav Balabaiev; unterstützt von Bürgermeister Oleksandr Senkewytsch, der Entwicklungsagentur und der Verwaltung des Bezirks Sawodskyj.',
              'en': 'The city paper names those involved: organiser Roland Bairozian, artist Viacheslav Balabaiev; supported by mayor Oleksandr Senkevych, the development agency and the Zavodskyi district administration.',
              'uk': 'Міська газета називає учасників: організатор Роланд Байрозян, художник В’ячеслав Балабаєв; підтримали мер Олександр Сєнкевич, Агенція розвитку та адміністрація Заводського району.'}, quotes=[]),
    dict(id='skatepark-podrobnosti', date='09.2019', outlet='Подробности (podrobnosti.mk.ua)', k=None, lang='ru', status='blocked', url='https://podrobnosti.mk.ua/article/v-nikolaeve-vozle-nadezdy-poavilos-bolsoe-graffiti', wayback=None,
         head='В Николаеве возле «Надежды» появилось большое граффити', imgs=[],
         sum={'de': 'Weiterer Bericht über das Skatepark-Graffiti bei der Sportschule „Nadeschda“.', 'en': 'Another report on the skate-park graffiti next to the Nadezhda sports school.', 'uk': 'Ще одна публікація про графіті на місці скейт-парку біля «Надії».'}, quotes=[]),
    dict(id='korabli-vn', date='14.09.2021', outlet='Вечірній Миколаїв (vn.mk.ua)', k='2021-09-vn-chess', lang='ru', status='ok', url='https://vn.mk.ua/ru/v-pamyat-o-korabelah-i-shahmatistah/',
         head='В память о корабелах и шахматистах', imgs=['smi-2021-09-vn-chess-02', 'smi-2021-09-vn-chess-00', 'smi-2021-09-vn-chess-03'],
         sum={'de': 'Die persönlichste Geschichte: Im Auftrag der Unternehmer-Plattform „MrijDij“ malt BVB an der Ecke Faleewska/Nabereschna drei Schiffe, die in Mykolajiw gebaut wurden – die Fregatte „Swjatyj Mykolaj“, einen Raketenkreuzer „Atlant“ und einen Flugzeugträger „Kretschet“. Die Zeitung nennt ihn „einen der Anführer der Graffiti-Kultur der Stadt“ mit 17 Jahren Erfahrung. Gegenüber dem Schachklub entstehen Schachfiguren – zu Ehren seines ersten Schachlehrers.',
              'en': 'The most personal story: commissioned by the business platform “MriyDiy”, BVB paints three ships built in Mykolaiv at the corner of Faleievska/Naberezhna – the frigate “Sviatyi Mykolai”, an “Atlant” missile cruiser and a “Krechet” aircraft carrier. The paper calls him “one of the leaders of the city’s graffiti culture” with 17 years of experience. Opposite the chess club he adds chess pieces – in honour of his first chess teacher.',
              'uk': 'Найособистіша історія: на замовлення бізнес-платформи «МрійДій» BVB малює на розі Фалеєвської та Набережної три збудовані в Миколаєві кораблі – фрегат «Святий Миколай», ракетний крейсер проєкту «Атлант» і авіаносець проєкту «Кречет». Газета називає його «одним із лідерів графіті-культури міста» з 17-річним досвідом. Навпроти шахового клубу – шахові фігури на честь першого шахового наставника.'},
         quotes=[('Наша семья имеет непосредственное отношение к николаевскому судостроению. Дедушка, Георгий Матвеевич Балабаев, десять лет возглавлял «Судостроительный завод имени 61-го коммунара», а отец строил авианосцы на ЧСЗ. Идея изобразить корабли, к которым родные люди имели непосредственное отношение, была осознанной и продуманной.',
                  {'de': 'Unsere Familie ist direkt mit dem Schiffbau in Mykolajiw verbunden. Mein Großvater, Heorhij Matwijowytsch Balabaiev, leitete zehn Jahre die Werft „61 Kommunarden“, mein Vater baute Flugzeugträger auf der Schwarzmeerwerft. Schiffe zu malen, mit denen meine Familie direkt zu tun hatte, war eine bewusste Entscheidung.',
                   'en': 'Our family is directly connected to Mykolaiv shipbuilding. My grandfather, Heorhii Matviiovych Balabaiev, ran the “61 Communards” shipyard for ten years, and my father built aircraft carriers at the Black Sea Shipyard. Painting ships my family was directly involved with was a deliberate, well-considered idea.',
                   'uk': 'Наша родина безпосередньо пов’язана з миколаївським суднобудуванням. Дідусь, Георгій Матвійович Балабаєв, десять років очолював суднобудівний завод імені 61 комунара, а батько будував авіаносці на ЧСЗ. Ідея зобразити кораблі, до яких рідні мали безпосередній стосунок, була свідомою й продуманою.'}),
                 ('Дедушка в 7 лет привел меня в клуб к Николаю Васильевичу Шелесту. Он научил меня играть в шахматы. Благодаря его наставничеству я получил разряд по шахматам. Чтобы как-то увековечить память Николая Шелеста, рядом с фигурой «Короля» будет написано его имя…',
                  {'de': 'Als ich sieben war, brachte mich mein Großvater in den Klub zu Mykola Wassyljowytsch Schelest. Er hat mir Schach beigebracht, dank ihm bekam ich eine Wertungsklasse. Um sein Andenken zu bewahren, steht neben der Figur des Königs sein Name.',
                   'en': 'When I was seven, my grandfather took me to Mykola Vasyliovych Shelest’s club. He taught me chess, and thanks to his mentoring I earned a rating class. To honour his memory, his name will be written next to the king.',
                   'uk': 'Дідусь у 7 років привів мене до клубу до Миколи Васильовича Шелеста. Він навчив мене грати в шахи, завдяки його наставництву я отримав розряд. Щоб увічнити його пам’ять, поруч із фігурою «Короля» буде написано його ім’я.'})]),
    dict(id='korabli-nikvesti', date='15.09.2021', outlet='НікВісті (nikvesti.com) · НІС-ТВ «Об’єктив»', k='2021-09-nikvesti', lang='ru', status='ok', url='https://nikvesti.com/ru/news/public/229497',
         head='Фрегат «Святой Николай», ракетный крейсер и авианосец, — в центре Николаева откроют новый мурал', imgs=['smi-2021-09-nikvesti-00'],
         sum={'de': 'Nachrichtenportal und TV-Beitrag (Sendung „Objektiv“, NIS-TV) über das Mural als Geschenk zum Stadtgeburtstag: zwei Teile – Schiffe und riesige Schachfiguren.',
              'en': 'News site and TV report (programme “Obiektyv”, NIS-TV) about the mural as a gift for the city’s birthday: two parts – ships and giant chess pieces.',
              'uk': 'Новинний сайт і телесюжет (програма «Об’єктив», НІС-ТВ) про мурал як подарунок до Дня міста: дві частини – кораблі й величезні шахові фігури.'},
         quotes=[('Хочу, чтобы люди помнили и гордились тем, что здесь было. Николаевцы строили эти корабли.',
                  {'de': 'Ich möchte, dass die Menschen sich erinnern und stolz sind auf das, was hier war. Die Menschen aus Mykolajiw haben diese Schiffe gebaut.',
                   'en': 'I want people to remember and be proud of what was here. The people of Mykolaiv built these ships.',
                   'uk': 'Хочу, щоб люди пам’ятали й пишалися тим, що тут було. Миколаївці будували ці кораблі.'})]),
    dict(id='korabli-ukrinform', date='20.09.2021', outlet='Укрінформ (ukrinform.ua)', k='2021-09-ukrinform', lang='uk', status='ok', url='https://www.ukrinform.ua/rubric-regions/3318771-u-mikolaevi-vidkrili-mural-iz-pobudovanimi-na-miscevih-zavodah-korablami.html',
         head='У Миколаєві відкрили мурал із побудованими на місцевих заводах кораблями', imgs=['smi-2021-09-ukrinform-00'],
         sum={'de': 'Die nationale Nachrichtenagentur berichtet über die Eröffnung: 150 m², rund 100.000 Hrywnja, komplett privat finanziert. Nach Kritik, die Schiffe ähnelten Einheiten der russischen Flotte, übermalte BVB eine Bordnummer und schrieb stattdessen den Namen des unvollendeten Kreuzers „Ukrajina“ auf das Schiff.',
              'en': 'The national news agency reports on the opening: 150 m², around 100,000 hryvnias, fully privately funded. After criticism that the ships resembled Russian navy vessels, BVB painted over a hull number and wrote the name of the unfinished cruiser “Ukraina” instead.',
              'uk': 'Національне інформагентство про відкриття: 150 м², близько 100 тис. грн, повністю за приватні кошти. Після критики, що кораблі нагадують судна флоту РФ, BVB зафарбував бортовий номер і написав назву недобудованого крейсера «Україна».'},
         quotes=[('Наше завдання надихнути людей і показати досягнення міста корабелів, звернути увагу на те, які кораблі тут будувалися свого часу.',
                  {'de': 'Unsere Aufgabe ist es, Menschen zu inspirieren und die Leistungen der Stadt der Schiffbauer zu zeigen – den Blick darauf zu lenken, welche Schiffe hier einst gebaut wurden.',
                   'en': 'Our task is to inspire people and show the achievements of the city of shipbuilders – to draw attention to the ships that were once built here.',
                   'uk': None})]),
    dict(id='korabli-suspilne', date='09.2021', outlet='Суспільне Миколаїв (suspilne.media)', k=None, lang='uk', status='blocked', url='https://suspilne.media/165035-u-mikolaevi-namaluvali-mural-prisvacenij-istoricnomu-minulomu-mista/', wayback=None,
         head='У Миколаєві відкрили корабельний мурал', imgs=[],
         sum={'de': 'Bericht des öffentlich-rechtlichen Senders. Laut Suchergebnis schildert BVB den Ablauf: Skizzen an einem Tag, eine Woche Wandvorbereitung, eine Woche Malen.',
              'en': 'Report by the public broadcaster. According to the search result, BVB describes the process: sketches in one day, one week preparing the wall, one week painting.',
              'uk': 'Сюжет Суспільного. За пошуковою видачею, BVB розповідає: ескізи за один день, тиждень на підготовку стіни, тиждень на реалізацію.'}, quotes=[]),
    dict(id='mykolaiv-future', date='23.11.2021', outlet='Mykolaiv Future (mykolaiv-future.com.ua)', k='mykolaiv-future-uk', lang='uk', status='ok', url='https://mykolaiv-future.com.ua/uk/articles-muraly-mykolayeva-slidamy-street-hudozhnykiv',
         head='Мурали Миколаєва: слідами street-художників', imgs=['smi-mykolaiv-future-uk-05', 'smi-mykolaiv-future-uk-06'],
         sum={'de': 'Überblick über die Street-Art Mykolajiws. Das Schiffs- und Schach-Mural ist eines der vorgestellten Werke; Viacheslav Balabaiev wird als „in Mykolajiw bekannter Street-Künstler“ genannt.',
              'en': 'Overview of Mykolaiv’s street art. The ships-and-chess mural is one of the featured works; Viacheslav Balabaiev is named as “a street artist well known in Mykolaiv”.',
              'uk': 'Огляд стріт-арту Миколаєва. Мурал із фрегатами й шаховими фігурами – серед представлених робіт; В’ячеслава Балабаєва названо «відомим у Миколаєві street-художником».'}, quotes=[]),
]

EPILOGUE = {'url': 'https://www.pravda.com.ua/eng/news/2025/06/26/7518827',
            'de': 'Im Juni 2025 stürzte nach russischen Drohnenangriffen ein Gebäude des Werks „Dormaschyna“ ein – des Ortes, an dem BVB ab 2007 die Hall of Fame betreute (Ukrajinska Prawda).',
            'en': 'In June 2025 a building of the Dormashyna plant collapsed after Russian drone attacks – the place where BVB curated the Hall of Fame from 2007 (Ukrainska Pravda).',
            'uk': 'У червні 2025 року після атак російських дронів обвалилася будівля заводу «Дормашина» – місця, де BVB з 2007 року курував Hall of Fame («Українська правда»).'}
