# Workshops page (DE/EN/UK) – facts taken from the magazine article "Graffiti-Workshop in Frankfurt" (articles.py, key 'workshop')
WS_PHOTOS = [44, 45, 47, 48, 46, 49, 50, 51, 52]   # gallery numbers (alts.py / gallery.py) – workshop photos live only on this page

WS = {
 'de': dict(
  meta=('Graffiti-Workshop Frankfurt – für Teams, Schulen & Kinder | Farbaholix',
        'Graffiti- und Hip-Hop-Workshops in Frankfurt: Teamevent für Firmen, Projekttag für Schulen, kreatives Erlebnis für Kinder. Auf Deutsch, Englisch, Ukrainisch und Russisch.'),
  focus='Graffiti Workshop Frankfurt',
  kicker='Workshops', h1='Graffiti-Workshop Frankfurt: Hip-Hop-Kultur zum Mitmachen',
  lead='Ein Graffiti-Workshop ist ein kreatives Erlebnis: Unter Anleitung von Slavik arbeiten die Teilnehmenden mit der Sprühdose – und nehmen am Ende ein gemeinsames Werk mit. Für Firmen, Schulen und Kinder in Frankfurt und Rhein-Main, auf Deutsch, Englisch, Ukrainisch und Russisch.',
  cta='Workshop anfragen',
  who_t='Für wen?',
  who=[('Teams & Firmen', 'Als Teambuilding, Firmenfeier oder Programmpunkt auf Konferenzen – mit einem Motiv, das später im Büro hängen kann.'),
       ('Schulen & Jugendzentren', 'Als Projekttag rund um Kunst und Hip-Hop.'),
       ('Kinder', 'Als kreatives Erlebnis – Slavik hat unter anderem Workshops im Internationalen Kinderhaus Frankfurt gegeben.')],
  learn_t='Was lernt man?',
  learn=['Den Umgang mit der Sprühdose: Druck, Abstand und verschiedene Caps.',
         'Buchstaben und Styles – von einfachen Letters bis zu ersten eigenen Entwürfen.',
         'Gemeinsam gestalten: Aus vielen Händen entsteht ein Bild.',
         'Hip-Hop-Kultur: Graffiti, DJing, B-Boying und MCing gehören zusammen.'],
  steps_t='So läuft ein Workshop ab',
  steps=[('Absprache', 'Gruppengröße, Ort und Ziel – etwa ein Motiv für Ihr Büro.'),
         ('Technik & Sicherheit', 'Kurze Einführung mit Schutzmasken, Handschuhen und Belüftung.'),
         ('Übung', 'Erste Versuche auf Probeflächen.'),
         ('Gemeinsames Werk', 'Das Ergebnis entsteht auf Leinwand oder an der Wand.')],
  photos_t='Eindrücke aus Workshops',
  faq=[('Braucht man Vorkenntnisse?', 'Nein. Der Workshop ist für Einsteiger gedacht; Fortgeschrittene bekommen anspruchsvollere Aufgaben.'),
       ('Findet der Workshop auch bei uns statt?', 'Ja, nach Absprache vor Ort bei Ihnen – drinnen auf Leinwänden oder draußen an einer Fläche, für die eine Erlaubnis vorliegt.'),
       ('In welchen Sprachen?', 'Auf Deutsch, Englisch, Ukrainisch und Russisch.')],
  more='Mehr im Magazin: Graffiti-Workshop als Teamevent →',
 ),
 'en': dict(
  meta=('Graffiti Workshop Frankfurt – for teams, schools & kids | Farbaholix',
        'Graffiti and hip-hop workshops in Frankfurt: a team event for companies, a project day for schools, a creative experience for kids. In German, English, Ukrainian and Russian.'),
  focus='graffiti workshop Frankfurt',
  kicker='Workshops', h1='Graffiti workshop Frankfurt: hip-hop culture, hands-on',
  lead='A graffiti workshop is a creative experience: guided by Slavik, participants work with spray cans – and take home a piece they made together. For companies, schools and kids in Frankfurt and the Rhine-Main area, in German, English, Ukrainian and Russian.',
  cta='Request a workshop',
  who_t='Who is it for?',
  who=[('Teams & companies', 'As team building, a company party or a conference programme item – with a motif that can later hang in your office.'),
       ('Schools & youth centres', 'As a project day around art and hip-hop.'),
       ('Kids', 'As a creative experience – among others, Slavik has run workshops at the Internationales Kinderhaus Frankfurt.')],
  learn_t='What do you learn?',
  learn=['Handling a spray can: pressure, distance and different caps.',
         'Letters and styles – from simple letters to first designs of your own.',
         'Creating together: many hands, one picture.',
         'Hip-hop culture: graffiti, DJing, b-boying and MCing belong together.'],
  steps_t='How a workshop works',
  steps=[('Planning', 'Group size, location and goal – for example a motif for your office.'),
         ('Technique & safety', 'A short introduction with masks, gloves and ventilation.'),
         ('Practice', 'First attempts on practice boards.'),
         ('The joint piece', 'The result is created on canvas or on a wall.')],
  photos_t='Impressions from workshops',
  faq=[('Do I need any experience?', 'No. The workshop is made for beginners; advanced participants get more demanding tasks.'),
       ('Can the workshop take place at our venue?', 'Yes, by arrangement at your place – indoors on canvases or outdoors on a surface with permission.'),
       ('In which languages?', 'German, English, Ukrainian and Russian.')],
  more='',
 ),
 'uk': dict(
  meta=("Графіті-воркшоп у Франкфурті – для команд, шкіл і дітей | Farbaholix",
        "Графіті- та хіп-хоп-воркшопи у Франкфурті: тимбілдинг для компаній, проєктний день для шкіл, творча пригода для дітей. Німецькою, англійською, українською та російською."),
  focus='графіті воркшоп Франкфурт',
  kicker='Воркшопи', h1="Графіті-воркшоп у Франкфурті: хіп-хоп-культура, яку можна спробувати",
  lead="Графіті-воркшоп – це творча пригода: під керівництвом Славіка учасники працюють із балончиком і наприкінці забирають спільну роботу. Для компаній, шкіл і дітей у Франкфурті та регіоні Райн-Майн – німецькою, англійською, українською та російською.",
  cta='Замовити воркшоп',
  who_t='Для кого?',
  who=[('Команди й компанії', "Як тимбілдинг, корпоратив чи пункт програми конференції – з мотивом, який потім може прикрасити офіс."),
       ('Школи й молодіжні центри', "Як проєктний день про мистецтво та хіп-хоп."),
       ('Діти', "Як творча пригода – Славік, зокрема, проводив воркшопи в Internationales Kinderhaus у Франкфурті.")],
  learn_t='Чого навчаться учасники?',
  learn=["Поводитися з балончиком: тиск, відстань і різні кепи.",
         "Букви та стилі – від простих літер до перших власних ескізів.",
         "Творити разом: багато рук – одна картина.",
         "Хіп-хоп-культура: графіті, діджеїнг, брейкінг і MCing – одне ціле."],
  steps_t='Як проходить воркшоп',
  steps=[('Домовленість', "Розмір групи, місце й мета – наприклад, мотив для вашого офісу."),
         ('Техніка й безпека', "Короткий вступ: маски, рукавички, провітрювання."),
         ('Практика', "Перші спроби на тренувальних поверхнях."),
         ('Спільна робота', "Результат з'являється на полотні або на стіні.")],
  photos_t='Моменти з воркшопів',
  faq=[('Чи потрібен досвід?', "Ні. Воркшоп розрахований на початківців; досвідчені отримують складніші завдання."),
       ('Чи можна провести воркшоп у нас?', "Так, за домовленістю на вашому майданчику – у приміщенні на полотнах або надворі на поверхні, для якої є дозвіл."),
       ('Якими мовами?', "Німецькою, англійською, українською та російською.")],
  more='',
 ),
}
